// Command registry — source of truth for capabilities and schema introspection

export interface CommandDef {
  name: string
  description: string
  safety: 'read' | 'write' | 'destructive'
  args?: Array<{ name: string; required: boolean; description: string }>
  flags?: Record<string, {
    type: 'string' | 'number' | 'boolean'
    alias?: string
    description: string
    default?: unknown
  }>
  examples?: string[]
}

export const COMMANDS: CommandDef[] = [
  // mail
  { name: 'mail list', description: 'List inbox threads', safety: 'read',
    flags: { query: { type: 'string', alias: 'q', description: 'Gmail search query', default: 'in:inbox' }, max: { type: 'number', description: 'Max results', default: 50 }, 'page-token': { type: 'string', description: 'Pagination token' } },
    examples: ['con mail list', "con mail list --query 'from:alice is:unread' --max 10"] },
  { name: 'mail read', description: 'Read a thread with messages', safety: 'read',
    args: [{ name: 'thread-id', required: true, description: 'Gmail thread ID' }],
    flags: { format: { type: 'string', description: 'Output format', default: 'plain' } } },
  { name: 'mail archive', description: 'Archive thread(s)', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail trash', description: 'Move thread(s) to trash', safety: 'destructive',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail snooze', description: 'Snooze a thread until later', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }],
    flags: { until: { type: 'string', description: 'Snooze until: later-today, tomorrow, next-week, monday, or ISO date' } } },
  { name: 'mail unsnooze', description: 'Unsnooze a thread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }] },
  { name: 'mail mark-read', description: 'Mark thread(s) as read', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail mark-unread', description: 'Mark thread(s) as unread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail reply', description: 'Reply to a thread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }],
    flags: { body: { type: 'string', description: 'Reply body text' }, html: { type: 'boolean', description: 'Body is HTML' }, 'reply-all': { type: 'boolean', description: 'Reply to all recipients' }, cc: { type: 'string', description: 'CC address(es)' } } },
  { name: 'mail forward', description: 'Forward a thread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }],
    flags: { to: { type: 'string', description: 'Recipient' }, body: { type: 'string', description: 'Additional body text' } } },
  { name: 'mail send', description: 'Send a new email', safety: 'write',
    flags: { to: { type: 'string', description: 'Recipient' }, subject: { type: 'string', description: 'Subject' }, body: { type: 'string', description: 'Body text' }, cc: { type: 'string', description: 'CC address' }, from: { type: 'string', description: 'From alias' }, html: { type: 'boolean', description: 'Body is HTML' }, attach: { type: 'string', description: 'File path(s) to attach' } },
    examples: ["con mail send --to alice@example.com --subject 'Hello' --body 'Hi there'"] },
  { name: 'mail attachments', description: 'List attachments for a thread', safety: 'read',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }] },
  { name: 'mail download', description: 'Download an attachment', safety: 'read',
    args: [{ name: 'message-id', required: true, description: 'Message ID' }, { name: 'attachment-id', required: true, description: 'Attachment ID' }],
    flags: { out: { type: 'string', description: 'Output file path' } } },
  { name: 'mail contacts', description: 'Search contacts', safety: 'read',
    args: [{ name: 'query', required: true, description: 'Search query' }] },
  { name: 'mail aliases', description: 'List send-as aliases', safety: 'read' },
  { name: 'mail undo', description: 'Undo last archive/trash', safety: 'write' },

  // chat
  { name: 'chat rooms', description: 'List chat rooms', safety: 'read',
    flags: { filter: { type: 'string', description: 'Filter: unread, all, favourites, snoozed', default: 'unread' } } },
  { name: 'chat messages', description: 'Read messages in a room', safety: 'read',
    args: [{ name: 'room-id', required: true, description: 'Matrix room ID' }],
    flags: { limit: { type: 'number', description: 'Max messages', default: 50 }, before: { type: 'string', description: 'Pagination token' } } },
  { name: 'chat send', description: 'Send a message to a room', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Matrix room ID' }],
    flags: { body: { type: 'string', description: 'Message text' }, html: { type: 'boolean', description: 'Body is HTML' }, 'reply-to': { type: 'string', description: 'Event ID to reply to' } } },
  { name: 'chat send-file', description: 'Send a file to a room', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }, { name: 'file-path', required: true, description: 'File to send' }],
    flags: { caption: { type: 'string', description: 'Caption text' } } },
  { name: 'chat react', description: 'React to a message', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }, { name: 'event-id', required: true, description: 'Event ID' }, { name: 'emoji', required: true, description: 'Emoji reaction' }] },
  { name: 'chat mark-read', description: 'Mark room(s) as read', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID(s)' }] },
  { name: 'chat mark-unread', description: 'Mark a room as unread', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }] },
  { name: 'chat snooze', description: 'Snooze a room', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }],
    flags: { until: { type: 'string', description: 'Snooze until' } } },
  { name: 'chat info', description: 'Get room details', safety: 'read',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }] },
  { name: 'chat tail', description: 'Stream new messages (NDJSON)', safety: 'read',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }] },
  { name: 'chat undo', description: 'Undo last mark-read', safety: 'write' },

  // bookmarks
  { name: 'bookmarks list', description: 'List bookmarks', safety: 'read',
    flags: { tag: { type: 'string', description: 'Filter by tag' }, search: { type: 'string', alias: 'q', description: 'Search query' }, limit: { type: 'number', description: 'Max results' } },
    examples: ['con bookmarks list', "con bookmarks list --tag dev/frontend --search react"] },
  { name: 'bookmarks get', description: 'Get bookmark details', safety: 'read',
    args: [{ name: 'filename', required: true, description: 'Bookmark filename (e.g. my-bookmark.md)' }] },
  { name: 'bookmarks tags', description: 'List all tags with counts', safety: 'read' },
  { name: 'bookmarks update', description: 'Update bookmark tags/title', safety: 'write',
    args: [{ name: 'filename', required: true, description: 'Bookmark filename' }],
    flags: { 'add-tag': { type: 'string', description: 'Tag(s) to add' }, 'remove-tag': { type: 'string', description: 'Tag(s) to remove' }, title: { type: 'string', description: 'New title' } } },
  { name: 'bookmarks delete', description: 'Delete a bookmark', safety: 'destructive',
    args: [{ name: 'filename', required: true, description: 'Bookmark filename' }] },
  { name: 'bookmarks reload', description: 'Force reload from disk', safety: 'read' },

  // notes
  { name: 'notes list', description: 'List vault files', safety: 'read',
    flags: { dir: { type: 'string', description: 'Subdirectory to list' } },
    examples: ['con notes list', 'con notes list --dir scratch'] },
  { name: 'notes read', description: 'Read a note', safety: 'read',
    args: [{ name: 'path', required: true, description: 'File path relative to vault root' }] },
  { name: 'notes write', description: 'Write/create a note', safety: 'write',
    args: [{ name: 'path', required: true, description: 'File path' }],
    flags: { content: { type: 'string', description: 'File content' }, stdin: { type: 'boolean', description: 'Read content from stdin' } } },
  { name: 'notes append', description: 'Append to a note', safety: 'write',
    args: [{ name: 'path', required: true, description: 'File path' }],
    flags: { content: { type: 'string', description: 'Content to append' } } },
  { name: 'notes delete', description: 'Delete a note', safety: 'destructive',
    args: [{ name: 'path', required: true, description: 'File path' }] },
  { name: 'notes rename', description: 'Rename/move a note', safety: 'write',
    args: [{ name: 'from', required: true, description: 'Current path' }, { name: 'to', required: true, description: 'New path' }] },
  { name: 'notes mkdir', description: 'Create a directory', safety: 'write',
    args: [{ name: 'path', required: true, description: 'Directory path' }] },
  { name: 'notes search', description: 'Search notes', safety: 'read',
    args: [{ name: 'query', required: true, description: 'Search query' }],
    flags: { mode: { type: 'string', description: 'Search mode: filename or content', default: 'filename' } } },
  { name: 'notes daily', description: 'Read or append to daily note', safety: 'write',
    flags: { content: { type: 'string', description: 'Content to append (omit to read)' } } },

  // feeds
  { name: 'feeds list', description: 'List feed subscriptions', safety: 'read',
    flags: { folder: { type: 'string', description: 'Filter by folder' } } },
  { name: 'feeds items', description: 'List feed items', safety: 'read',
    flags: { feed: { type: 'string', description: 'Filter by feed ID' }, folder: { type: 'string', description: 'Filter by folder' }, unread: { type: 'boolean', description: 'Show unread only' }, since: { type: 'string', description: 'Items since date (ISO)' }, limit: { type: 'number', description: 'Max results', default: 50 } } },
  { name: 'feeds read', description: 'Read a feed item', safety: 'read',
    args: [{ name: 'item-id', required: true, description: 'Feed item ID' }] },
  { name: 'feeds mark-read', description: 'Mark items as read', safety: 'write',
    flags: { item: { type: 'string', description: 'Item ID' }, feed: { type: 'string', description: 'Feed ID (mark all in feed)' }, folder: { type: 'string', description: 'Folder (mark all in folder)' }, all: { type: 'boolean', description: 'Mark everything read' } } },
  { name: 'feeds mark-unread', description: 'Mark an item as unread', safety: 'write',
    args: [{ name: 'item-id', required: true, description: 'Item ID' }] },
  { name: 'feeds add', description: 'Subscribe to a feed', safety: 'write',
    args: [{ name: 'url', required: true, description: 'Feed URL' }],
    flags: { title: { type: 'string', description: 'Feed title' }, folder: { type: 'string', description: 'Folder name' }, 'full-text': { type: 'boolean', description: 'Fetch full article text' } } },
  { name: 'feeds delete', description: 'Unsubscribe from a feed', safety: 'destructive',
    args: [{ name: 'feed-id', required: true, description: 'Feed ID' }] },
  { name: 'feeds import', description: 'Import feeds from OPML', safety: 'write',
    args: [{ name: 'opml-file', required: true, description: 'Path to OPML file' }] },
  { name: 'feeds export', description: 'Export feeds as OPML', safety: 'read',
    flags: { out: { type: 'string', description: 'Output file path' } } },

  // cal
  { name: 'cal calendars', description: 'List calendars', safety: 'read',
    flags: { account: { type: 'string', description: 'Filter by account email' } } },
  { name: 'cal events', description: 'List events', safety: 'read',
    flags: { from: { type: 'string', description: 'Start date' }, to: { type: 'string', description: 'End date' }, calendar: { type: 'string', description: 'Calendar ID' }, account: { type: 'string', description: 'Account email' } },
    examples: ['con cal events --from today --to +7d'] },
  { name: 'cal get', description: 'Get event details', safety: 'read',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal create', description: 'Create an event', safety: 'write',
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, title: { type: 'string', description: 'Event title' }, start: { type: 'string', description: 'Start datetime' }, end: { type: 'string', description: 'End datetime' }, account: { type: 'string', description: 'Account email' }, description: { type: 'string', description: 'Description' }, location: { type: 'string', description: 'Location' }, 'all-day': { type: 'boolean', description: 'All-day event' } } },
  { name: 'cal edit', description: 'Edit an event', safety: 'write',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, title: { type: 'string', description: 'New title' }, start: { type: 'string', description: 'New start' }, end: { type: 'string', description: 'New end' }, account: { type: 'string', description: 'Account email' }, 'this-only': { type: 'boolean', description: 'Edit only this instance' }, 'all-events': { type: 'boolean', description: 'Edit all instances' } } },
  { name: 'cal delete', description: 'Delete an event', safety: 'destructive',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal rsvp', description: 'RSVP to an event', safety: 'write',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, status: { type: 'string', description: 'accept, maybe, or decline' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal location', description: 'Set working location', safety: 'write',
    flags: { date: { type: 'string', description: 'Date' }, type: { type: 'string', description: 'home, office, or custom' }, label: { type: 'string', description: 'Custom location label' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal accounts', description: 'List calendar accounts', safety: 'read' },
  { name: 'cal add-account', description: 'Add a calendar account', safety: 'write' },
  { name: 'cal remove-account', description: 'Remove a calendar account', safety: 'destructive',
    args: [{ name: 'email', required: true, description: 'Account email' }] },

  // agent
  { name: 'agent list', description: 'List agent sessions', safety: 'read',
    flags: { past: { type: 'boolean', description: 'Include past sessions' }, cwd: { type: 'string', description: 'Working directory' } } },
  { name: 'agent create', description: 'Create a new agent session', safety: 'write',
    args: [{ name: 'prompt', required: true, description: 'Initial prompt' }],
    flags: { cwd: { type: 'string', description: 'Working directory' }, wait: { type: 'boolean', description: 'Block until complete' } } },
  { name: 'agent send', description: 'Send a message to a session', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }, { name: 'message', required: true, description: 'Message text' }] },
  { name: 'agent resume', description: 'Resume a past session', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }],
    flags: { prompt: { type: 'string', description: 'Resume prompt' }, cwd: { type: 'string', description: 'Working directory' } } },
  { name: 'agent kill', description: 'Kill a session', safety: 'destructive',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },
  { name: 'agent interrupt', description: 'Interrupt a session', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },
  { name: 'agent approve', description: 'Approve tool use', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }, { name: 'request-id', required: true, description: 'Request ID' }],
    flags: { input: { type: 'string', description: 'Modified input JSON' } } },
  { name: 'agent deny', description: 'Deny tool use', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }, { name: 'request-id', required: true, description: 'Request ID' }],
    flags: { reason: { type: 'string', description: 'Denial reason' } } },
  { name: 'agent tail', description: 'Stream session output (NDJSON)', safety: 'read',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },
  { name: 'agent wait', description: 'Block until session completes', safety: 'read',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },

  // search
  { name: 'search', description: 'Cross-service search', safety: 'read',
    args: [{ name: 'query', required: true, description: 'Search query' }],
    flags: { scope: { type: 'string', description: 'Comma-separated: mail,chat,notes,bookmarks,feeds', default: 'mail,chat,notes,bookmarks,feeds' }, limit: { type: 'number', description: 'Max results per service', default: 10 } } },

  // auth
  { name: 'auth login', description: 'Connect an account', safety: 'write',
    args: [{ name: 'provider', required: true, description: 'google or matrix' }],
    flags: { account: { type: 'string', description: 'Account hint' } } },
  { name: 'auth logout', description: 'Disconnect an account', safety: 'destructive',
    args: [{ name: 'provider', required: true, description: 'google or matrix' }],
    flags: { account: { type: 'string', description: 'Account email' } } },
  { name: 'auth status', description: 'Show authentication status', safety: 'read' },
  { name: 'auth accounts', description: 'List all connected accounts', safety: 'read' },

  // money
  { name: 'money status', description: 'Monzo connection status', safety: 'read' },
  { name: 'money accounts', description: 'List Monzo accounts', safety: 'read' },
  { name: 'money balance', description: 'Current account balance', safety: 'read' },
  { name: 'money transactions', description: 'List transactions (cached)', safety: 'read',
    flags: { since: { type: 'string', description: 'ISO date' }, before: { type: 'string', description: 'ISO date' },
      category: { type: 'string', description: 'Monzo category' }, search: { type: 'string', description: 'Search text' },
      limit: { type: 'string', description: 'Max results (default 50)' }, offset: { type: 'string', description: 'Offset' } } },
  { name: 'money get', description: 'Get single transaction detail', safety: 'read',
    args: [{ name: 'tx-id', required: true, description: 'Transaction ID' }] },
  { name: 'money pots', description: 'List pots with balances', safety: 'read' },
  { name: 'money deposit', description: 'Deposit to pot', safety: 'write',
    flags: { pot: { type: 'string', description: 'Pot ID (required)' }, amount: { type: 'string', description: 'Amount in pence (required)' } } },
  { name: 'money withdraw', description: 'Withdraw from pot', safety: 'write',
    flags: { pot: { type: 'string', description: 'Pot ID (required)' }, amount: { type: 'string', description: 'Amount in pence (required)' } } },
  { name: 'money annotate', description: 'Annotate transaction metadata', safety: 'write',
    args: [{ name: 'tx-id', required: true, description: 'Transaction ID' }],
    flags: { key: { type: 'string', description: 'Metadata key (required)' }, value: { type: 'string', description: 'Metadata value' } } },
  { name: 'money spending', description: 'Spending breakdown by category', safety: 'read',
    flags: { month: { type: 'string', description: 'YYYY-MM (default current)' } } },
  { name: 'money sync', description: 'Trigger transaction sync', safety: 'write' },

  // system
  { name: 'status', description: 'Hub health and sync status', safety: 'read' },
  { name: 'capabilities', description: 'List all commands for agent discovery', safety: 'read' },
  { name: 'schema', description: 'JSONSchema for any command', safety: 'read',
    args: [{ name: 'command', required: false, description: 'Command name (e.g. mail.list)' }] },
  { name: 'version', description: 'Show CLI version', safety: 'read' },
]

// Service aliases
export const ALIASES: Record<string, string> = {
  m: 'mail',
  c: 'chat',
  b: 'bookmarks',
  n: 'notes',
  f: 'feeds',
  a: 'agent',
  s: 'search',
  mo: 'money',
}
