// Command registry — source of truth for capabilities and schema introspection

export interface CommandDef {
  name: string
  description: string
  safety: 'read' | 'write' | 'destructive'
  args?: Array<{ name: string; required: boolean; description: string }>
  flags?: Record<string, {
    type: 'string' | 'number' | 'boolean'
    alias?: string
    description: string
    default?: unknown
  }>
  examples?: string[]
}

export const COMMANDS: CommandDef[] = [
  // mail
  { name: 'mail list', description: 'List inbox threads', safety: 'read',
    flags: { query: { type: 'string', alias: 'q', description: 'Gmail search query', default: 'in:inbox' }, max: { type: 'number', description: 'Max results', default: 50 }, 'page-token': { type: 'string', description: 'Pagination token' } },
    examples: ['con mail list', "con mail list --query 'from:alice is:unread' --max 10"] },
  { name: 'mail read', description: 'Read a thread with messages', safety: 'read',
    args: [{ name: 'thread-id', required: true, description: 'Gmail thread ID' }],
    flags: { format: { type: 'string', description: 'Output format', default: 'plain' } } },
  { name: 'mail archive', description: 'Archive thread(s)', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail trash', description: 'Move thread(s) to trash', safety: 'destructive',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail snooze', description: 'Snooze a thread until later', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }],
    flags: { until: { type: 'string', description: 'Snooze until: later-today, tomorrow, next-week, monday, or ISO date' } } },
  { name: 'mail unsnooze', description: 'Unsnooze a thread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }] },
  { name: 'mail mark-read', description: 'Mark thread(s) as read', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail mark-unread', description: 'Mark thread(s) as unread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail reply', description: 'Reply to a thread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }],
    flags: { body: { type: 'string', description: 'Reply body text' }, html: { type: 'boolean', description: 'Body is HTML' }, 'reply-all': { type: 'boolean', description: 'Reply to all recipients' }, cc: { type: 'string', description: 'CC address(es)' } } },
  { name: 'mail forward', description: 'Forward a thread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }],
    flags: { to: { type: 'string', description: 'Recipient' }, body: { type: 'string', description: 'Additional body text' } } },
  { name: 'mail send', description: 'Send a new email', safety: 'write',
    flags: { to: { type: 'string', description: 'Recipient' }, subject: { type: 'string', description: 'Subject' }, body: { type: 'string', description: 'Body text' }, cc: { type: 'string', description: 'CC address' }, from: { type: 'string', description: 'From alias' }, html: { type: 'boolean', description: 'Body is HTML' }, attach: { type: 'string', description: 'File path(s) to attach' } },
    examples: ["con mail send --to alice@example.com --subject 'Hello' --body 'Hi there'"] },
  { name: 'mail attachments', description: 'List attachments for a thread', safety: 'read',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }] },
  { name: 'mail download', description: 'Download an attachment', safety: 'read',
    args: [{ name: 'message-id', required: true, description: 'Message ID' }, { name: 'attachment-id', required: true, description: 'Attachment ID' }],
    flags: { out: { type: 'string', description: 'Output file path' } } },
  { name: 'mail contacts', description: 'Search contacts', safety: 'read',
    args: [{ name: 'query', required: true, description: 'Search query' }] },
  { name: 'mail aliases', description: 'List send-as aliases', safety: 'read' },
  { name: 'mail undo', description: 'Undo last archive/trash', safety: 'write' },

  // chat
  { name: 'chat rooms', description: 'List chat rooms', safety: 'read',
    flags: {
      filter: { type: 'string', description: 'Filter: unread, all, favourites, snoozed', default: 'unread' },
      network: { type: 'string', description: 'Bridge network: linkedin, whatsapp, signal, telegram, slack, discord, instagram, facebook, twitter, googlechat, gmessages, imessage' },
    } },
  { name: 'chat messages', description: 'Read messages in a room', safety: 'read',
    args: [{ name: 'room-id', required: true, description: 'Matrix room ID' }],
    flags: { limit: { type: 'number', description: 'Max messages', default: 50 }, before: { type: 'string', description: 'Pagination token' } } },
  { name: 'chat send', description: 'Send a message to a room', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Matrix room ID' }],
    flags: { body: { type: 'string', description: 'Message text' }, html: { type: 'boolean', description: 'Body is HTML' }, 'reply-to': { type: 'string', description: 'Event ID to reply to' } } },
  { name: 'chat send-file', description: 'Send a file to a room', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }, { name: 'file-path', required: true, description: 'File to send' }],
    flags: { caption: { type: 'string', description: 'Caption text' } } },
  { name: 'chat react', description: 'React to a message', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }, { name: 'event-id', required: true, description: 'Event ID' }, { name: 'emoji', required: true, description: 'Emoji reaction' }] },
  { name: 'chat mark-read', description: 'Mark room(s) as read', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID(s)' }] },
  { name: 'chat mark-unread', description: 'Mark a room as unread', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }] },
  { name: 'chat snooze', description: 'Snooze a room', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }],
    flags: { until: { type: 'string', description: 'Snooze until' } } },
  { name: 'chat info', description: 'Get room details', safety: 'read',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }] },
  { name: 'chat tail', description: 'Stream new messages (NDJSON)', safety: 'read',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }] },
  { name: 'chat undo', description: 'Undo last mark-read', safety: 'write' },

  // bookmarks
  { name: 'bookmarks list', description: 'List bookmarks', safety: 'read',
    flags: { tag: { type: 'string', description: 'Filter by tag' }, search: { type: 'string', alias: 'q', description: 'Search query' }, limit: { type: 'number', description: 'Max results' } },
    examples: ['con bookmarks list', "con bookmarks list --tag dev/frontend --search react"] },
  { name: 'bookmarks get', description: 'Get bookmark details', safety: 'read',
    args: [{ name: 'filename', required: true, description: 'Bookmark filename (e.g. my-bookmark.md)' }] },
  { name: 'bookmarks tags', description: 'List all tags with counts', safety: 'read' },
  { name: 'bookmarks update', description: 'Update bookmark tags/title', safety: 'write',
    args: [{ name: 'filename', required: true, description: 'Bookmark filename' }],
    flags: { 'add-tag': { type: 'string', description: 'Tag(s) to add' }, 'remove-tag': { type: 'string', description: 'Tag(s) to remove' }, title: { type: 'string', description: 'New title' } } },
  { name: 'bookmarks delete', description: 'Delete a bookmark', safety: 'destructive',
    args: [{ name: 'filename', required: true, description: 'Bookmark filename' }] },
  { name: 'bookmarks reload', description: 'Force reload from disk', safety: 'read' },

  // notes
  { name: 'notes list', description: 'List vault files', safety: 'read',
    flags: { dir: { type: 'string', description: 'Subdirectory to list' } },
    examples: ['con notes list', 'con notes list --dir scratch'] },
  { name: 'notes read', description: 'Read a note', safety: 'read',
    args: [{ name: 'path', required: true, description: 'File path relative to vault root' }] },
  { name: 'notes write', description: 'Write/create a note', safety: 'write',
    args: [{ name: 'path', required: true, description: 'File path' }],
    flags: { content: { type: 'string', description: 'File content' }, stdin: { type: 'boolean', description: 'Read content from stdin' } } },
  { name: 'notes append', description: 'Append to a note', safety: 'write',
    args: [{ name: 'path', required: true, description: 'File path' }],
    flags: { content: { type: 'string', description: 'Content to append' } } },
  { name: 'notes delete', description: 'Delete a note', safety: 'destructive',
    args: [{ name: 'path', required: true, description: 'File path' }] },
  { name: 'notes rename', description: 'Rename/move a note', safety: 'write',
    args: [{ name: 'from', required: true, description: 'Current path' }, { name: 'to', required: true, description: 'New path' }] },
  { name: 'notes mkdir', description: 'Create a directory', safety: 'write',
    args: [{ name: 'path', required: true, description: 'Directory path' }] },
  { name: 'notes search', description: 'Search notes', safety: 'read',
    args: [{ name: 'query', required: true, description: 'Search query' }],
    flags: { mode: { type: 'string', description: 'Search mode: filename or content', default: 'filename' } } },
  { name: 'notes daily', description: 'Read or append to daily note', safety: 'write',
    flags: { content: { type: 'string', description: 'Content to append (omit to read)' } } },

  // feeds
  { name: 'feeds list', description: 'List feed subscriptions', safety: 'read',
    flags: { folder: { type: 'string', description: 'Filter by folder' } } },
  { name: 'feeds items', description: 'List feed items', safety: 'read',
    flags: { feed: { type: 'string', description: 'Filter by feed ID' }, folder: { type: 'string', description: 'Filter by folder' }, unread: { type: 'boolean', description: 'Show unread only' }, since: { type: 'string', description: 'Items since date (ISO)' }, limit: { type: 'number', description: 'Max results', default: 50 } } },
  { name: 'feeds read', description: 'Read a feed item', safety: 'read',
    args: [{ name: 'item-id', required: true, description: 'Feed item ID' }] },
  { name: 'feeds mark-read', description: 'Mark items as read', safety: 'write',
    flags: { item: { type: 'string', description: 'Item ID' }, feed: { type: 'string', description: 'Feed ID (mark all in feed)' }, folder: { type: 'string', description: 'Folder (mark all in folder)' }, all: { type: 'boolean', description: 'Mark everything read' } } },
  { name: 'feeds mark-unread', description: 'Mark an item as unread', safety: 'write',
    args: [{ name: 'item-id', required: true, description: 'Item ID' }] },
  { name: 'feeds add', description: 'Subscribe to a feed', safety: 'write',
    args: [{ name: 'url', required: true, description: 'Feed URL' }],
    flags: { title: { type: 'string', description: 'Feed title' }, folder: { type: 'string', description: 'Folder name' }, 'full-text': { type: 'boolean', description: 'Fetch full article text' } } },
  { name: 'feeds delete', description: 'Unsubscribe from a feed', safety: 'destructive',
    args: [{ name: 'feed-id', required: true, description: 'Feed ID' }] },
  { name: 'feeds import', description: 'Import feeds from OPML', safety: 'write',
    args: [{ name: 'opml-file', required: true, description: 'Path to OPML file' }] },
  { name: 'feeds export', description: 'Export feeds as OPML', safety: 'read',
    flags: { out: { type: 'string', description: 'Output file path' } } },

  // cal
  { name: 'cal calendars', description: 'List calendars', safety: 'read',
    flags: { account: { type: 'string', description: 'Filter by account email' } } },
  { name: 'cal events', description: 'List events', safety: 'read',
    flags: { from: { type: 'string', description: 'Start date' }, to: { type: 'string', description: 'End date' }, calendar: { type: 'string', description: 'Calendar ID' }, account: { type: 'string', description: 'Account email' } },
    examples: ['con cal events --from today --to +7d'] },
  { name: 'cal get', description: 'Get event details', safety: 'read',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal create', description: 'Create an event', safety: 'write',
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, title: { type: 'string', description: 'Event title' }, start: { type: 'string', description: 'Start datetime' }, end: { type: 'string', description: 'End datetime' }, account: { type: 'string', description: 'Account email' }, description: { type: 'string', description: 'Description' }, location: { type: 'string', description: 'Location' }, 'all-day': { type: 'boolean', description: 'All-day event' } } },
  { name: 'cal edit', description: 'Edit an event', safety: 'write',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, title: { type: 'string', description: 'New title' }, start: { type: 'string', description: 'New start' }, end: { type: 'string', description: 'New end' }, account: { type: 'string', description: 'Account email' }, 'this-only': { type: 'boolean', description: 'Edit only this instance' }, 'all-events': { type: 'boolean', description: 'Edit all instances' } } },
  { name: 'cal delete', description: 'Delete an event', safety: 'destructive',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal rsvp', description: 'RSVP to an event', safety: 'write',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, status: { type: 'string', description: 'accept, maybe, or decline' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal location', description: 'Set working location', safety: 'write',
    flags: { date: { type: 'string', description: 'Date' }, type: { type: 'string', description: 'home, office, or custom' }, label: { type: 'string', description: 'Custom location label' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal accounts', description: 'List calendar accounts', safety: 'read' },
  { name: 'cal add-account', description: 'Add a calendar account', safety: 'write' },
  { name: 'cal remove-account', description: 'Remove a calendar account', safety: 'destructive',
    args: [{ name: 'email', required: true, description: 'Account email' }] },

  // cal flights — SerpApi-backed flight search & watchlists (see CLAUDE.md)
  { name: 'cal flights status', description: 'Show SerpApi credential status', safety: 'read' },
  { name: 'cal flights credentials', description: 'Set/rotate the SerpApi key', safety: 'write',
    flags: { key: { type: 'string', description: 'SerpApi API key' } } },
  { name: 'cal flights explore', description: 'Anywhere/region flight discovery (Google Travel Explore engine)', safety: 'read',
    flags: {
      from: { type: 'string', description: 'Origin airport code (e.g. LHR) — required' },
      to: { type: 'string', description: 'Specific destination code (optional)' },
      region: { type: 'string', description: 'europe|africa|asia|oceania|northAmerica|southAmerica' },
      month: { type: 'string', description: '1..12 or 0 for next six months (default 0)' },
      duration: { type: 'string', description: 'Weekend | "1 week" | "2 weeks" (default "1 week")' },
      currency: { type: 'string', description: 'ISO currency (default GBP)' },
    },
    examples: ['con cal flights explore --from LHR --region europe --month 11', 'con cal flights explore --from STN --to BCN --month 12'] },
  { name: 'cal flights search', description: 'Point-to-point flight search (Google Flights engine)', safety: 'read',
    flags: {
      from: { type: 'string', description: 'Origin code — required' },
      to: { type: 'string', description: 'Destination code — required' },
      date: { type: 'string', description: 'YYYY-MM-DD outbound — required' },
      return: { type: 'string', description: 'YYYY-MM-DD return (omit for one-way)' },
      class: { type: 'string', description: '1 economy | 2 premium | 3 business | 4 first' },
      adults: { type: 'string', description: 'Adult passengers (default 1)' },
      currency: { type: 'string', description: 'ISO currency (default GBP)' },
    },
    examples: ['con cal flights search --from LHR --to JFK --date 2026-08-15 --return 2026-08-22'] },
  { name: 'cal flights watch', description: 'Manage flight price watchlists',
    safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list (default) | add | remove | run' }],
    flags: {
      kind: { type: 'string', description: 'explore | route (auto-detected from --date if omitted)' },
      from: { type: 'string', description: 'Origin code' },
      to: { type: 'string', description: 'Destination code' },
      region: { type: 'string', description: 'Explore region (europe etc)' },
      month: { type: 'string', description: 'Explore month 1..12 or 0' },
      duration: { type: 'string', description: 'Explore duration (Weekend|1 week|2 weeks)' },
      date: { type: 'string', description: 'Route outbound date YYYY-MM-DD' },
      return: { type: 'string', description: 'Route return date' },
      class: { type: 'string', description: 'Route travel class 1..4' },
      adults: { type: 'string', description: 'Route adults (default 1)' },
      label: { type: 'string', description: 'Friendly label' },
      max: { type: 'string', description: 'Alert threshold in major units (e.g. 250)' },
      currency: { type: 'string', description: 'ISO currency (default GBP)' },
    },
    examples: [
      'con cal flights watch list',
      'con cal flights watch add --from LHR --region europe --month 11 --max 200 --label "Nov Europe"',
      'con cal flights watch add --from LHR --to JFK --date 2026-08-15 --return 2026-08-22 --max 600',
      'con cal flights watch run wl_abcdef',
      'con cal flights watch remove wl_abcdef',
    ] },
  { name: 'map flights', description: 'Render flight legs as animated great-circle arcs on the Map tab (its own toggle-able layer, labelled with price + date). Legs = JSON array of {from,to,price?,currency?,date?,flight?,label?,color?}.', safety: 'write',
    args: [{ name: 'verb', required: false, description: 'push (default) | clear' }],
    flags: {
      name: { type: 'string', description: 'Layer name (slug under flights/); default "trip"' },
      legs: { type: 'string', description: 'Inline JSON array of legs' },
      file: { type: 'string', description: 'Read legs JSON from a file' },
      stdin: { type: 'boolean', description: 'Read legs JSON from stdin' },
      color: { type: 'string', description: 'Default arc colour (hex)' },
      fit: { type: 'string', description: 'false to not auto-zoom to the arcs' },
    },
    examples: [
      'echo \'[{"from":"LHR","to":"AMS","price":73,"date":"2026-07-04"},{"from":"AMS","to":"FRA","price":126,"date":"2026-07-07"}]\' | con map flights push --name plan-c --stdin',
      'con map flights clear',
    ] },

  // agent
  { name: 'agent list', description: 'List agent sessions', safety: 'read',
    flags: { past: { type: 'boolean', description: 'Include past sessions' }, cwd: { type: 'string', description: 'Working directory' } } },
  { name: 'agent create', description: 'Create a new agent session', safety: 'write',
    args: [{ name: 'prompt', required: true, description: 'Initial prompt' }],
    flags: { cwd: { type: 'string', description: 'Working directory' }, wait: { type: 'boolean', description: 'Block until complete' } } },
  { name: 'agent send', description: 'Send a message to a session', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }, { name: 'message', required: true, description: 'Message text' }] },
  { name: 'agent resume', description: 'Resume a past session', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }],
    flags: { prompt: { type: 'string', description: 'Resume prompt' }, cwd: { type: 'string', description: 'Working directory' } } },
  { name: 'agent kill', description: 'Kill a session', safety: 'destructive',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },
  { name: 'agent reload', description: "Reload a session WITHOUT bouncing the hub: respawn its subprocess (history preserved). Pass \"Al\" to re-derive his persona from AL.md (a genuinely fresh spawn — the lever for applying persona/AL.md edits); works whether Al is up or down. Accepts a session id or a unique name.", safety: 'write',
    args: [{ name: 'session-id|name|Al', required: true, description: 'Session id, unique name, or "Al"' }],
    examples: ['con agent reload Al', 'con agent reload session_12_1781...'] },
  { name: 'agent interrupt', description: 'Interrupt a session', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },
  { name: 'agent approve', description: 'Approve tool use', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }, { name: 'request-id', required: true, description: 'Request ID' }],
    flags: { input: { type: 'string', description: 'Modified input JSON' } } },
  { name: 'agent deny', description: 'Deny tool use', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }, { name: 'request-id', required: true, description: 'Request ID' }],
    flags: { reason: { type: 'string', description: 'Denial reason' } } },
  { name: 'agent tail', description: 'Stream session output (NDJSON)', safety: 'read',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },
  { name: 'agent wait', description: 'Block until session completes', safety: 'read',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },
  { name: 'agent chat', description: 'Talk to another agent: forks the named session (inherits its context), injects your message, returns its reply. The fork is a normal session (see `agent list`). Continue with --id, end with --id --end.', safety: 'write',
    args: [
      { name: 'name', required: false, description: 'Target session name (first turn). Omit when using --id.' },
      { name: 'message', required: false, description: 'Message to send. Omit only with --end.' },
    ],
    flags: {
      id: { type: 'string', description: 'Continue an existing conversation (the conv id = fork claudeSessionId printed on the first turn)' },
      end: { type: 'boolean', description: 'End the conversation fork (with --id)' },
      merge: { type: 'boolean', description: 'Merge the fork back into its parent (fork summarises → parent absorbs), then close it — the reversible alternative to --end (with --id)' },
      from: { type: 'string', description: 'Your own name, shown to the other agent on the first turn (default: "another agent")' },
      timeout: { type: 'string', description: 'Max wait for a reply, e.g. 5m, 90s (default 5m)' },
    },
    examples: [
      'con agent chat "Gravel general" "what auth does the control plane use?"',
      'con agent chat --id 3c7ac00e-… "and how are keys rotated?"',
      'con agent chat --id 3c7ac00e-… --merge',
    ] },
  { name: 'agent merge', description: 'Merge a fork back into its parent: the fork self-summarises what it learned/did, that digest is injected into the parent session, then the fork is closed. Use instead of killing a fork when its findings should survive. Accepts a hub session id, a conv id (fork claudeSessionId), or a unique name.', safety: 'write',
    args: [{ name: 'session', required: true, description: 'Fork to merge (session id / conv id / name)' }],
    examples: ['con agent merge session_47_1781…', 'con agent merge 6ecfb8ec-…'] },
  { name: 'agent model', description: 'Inspect or switch the Claude model all hub agents spawn with. Recovery lever when a model is pulled: `set` changes it live (no code edit) and restarts sessions onto it; the hub also auto-falls-back down the chain on a model-unavailable error.', safety: 'write',
    args: [
      { name: 'subcommand', required: false, description: '`get` (default) or `set`' },
      { name: 'model-id', required: false, description: 'Model id for `set`, e.g. claude-opus-4-8' },
    ],
    examples: [
      'con agent model',
      'con agent model set claude-opus-4-8',
    ] },
  { name: 'agent role', description: 'Inspect/maintain durable org-chart roles. Each agent is a role backed by ~/.config/console/agents/<key>.md (title/manager/goals frontmatter + charter/Memory body). Charter, goals and memory are AGENT-owned — edit the .md directly; the CLI only reads them and writes the `manager` reporting edge.', safety: 'write',
    args: [
      { name: 'subcommand', required: false, description: '`list`|`tree` (default), `get <key>`, `manager <key> <mgr|--root>`, `delete <key>`' },
      { name: 'key', required: false, description: 'Role key (filename without .md)' },
      { name: 'manager', required: false, description: 'Manager role key, or --root to detach' },
    ],
    examples: [
      'con agent role',
      'con agent role get feeds-tab',
      'con agent role manager feeds-tab al',
      'con agent role manager feeds-tab --root',
    ] },
  { name: 'agent revive', description: 'Spawn a fresh session for a parked role (one with no live session). Its charter + memory are injected from its role file.', safety: 'write',
    args: [{ name: 'key', required: true, description: 'Role key to revive' }],
    examples: ['con agent revive feeds-tab'] },
  { name: 'agent delegate', description: 'Delegate a task DOWN the org to a role. Creates a task, wakes the assignee with a self-instructing envelope, returns the task id; async (non-blocking). The assignee reports back up with `con agent report`. Use --new to mint a role on the fly, --ephemeral for a throwaway parallel worker.', safety: 'write',
    args: [
      { name: 'toKey', required: false, description: 'Assignee role key (omit when using --new)' },
      { name: 'brief', required: true, description: 'The instruction (quote it)' },
    ],
    flags: {
      title: { type: 'string', description: 'Short task title (defaults to the brief)' },
      from: { type: 'string', description: 'Delegator role key (default: al)' },
      parent: { type: 'string', description: 'Parent task id (for a sub-delegation; report bubbles to it)' },
      ephemeral: { type: 'boolean', description: 'Spawn a fresh role-less worker instead of the durable role session' },
      new: { type: 'string', description: 'Mint a new role with this title and delegate to it' },
      cwd: { type: 'string', description: 'cwd for the new role (with --new)' },
      manager: { type: 'string', description: 'Manager for the new role (with --new; defaults to the delegator)' },
    },
    examples: [
      'con agent delegate feeds-tab "add a dark-mode toggle to the reader"',
      'con agent delegate "research X" --new "X researcher" --cwd /home/amar/proj/x',
    ] },
  { name: 'agent report', description: 'Report a task result UP to its delegator (wakes their session). Run this when work delegated to you is done/blocked.', safety: 'write',
    args: [
      { name: 'taskId', required: true, description: 'Task id (from the [DELEGATED TASK] envelope)' },
      { name: 'result', required: true, description: 'Concise result text (quote it)' },
    ],
    flags: { status: { type: 'string', description: 'done (default) | blocked | failed' } },
    examples: ['con agent report tsk_abc123 "shipped — dark-mode toggle in FeedItemView, verified on APK"'] },
  { name: 'agent tasks', description: 'List delegation tasks (what you owe / are owed). Filter with flags; `cancel <id>` cancels one.', safety: 'read',
    args: [{ name: 'subcommand', required: false, description: '`cancel <taskId>` to cancel a task' }],
    flags: {
      open: { type: 'boolean', description: 'Only non-terminal tasks' },
      assigned: { type: 'string', description: 'Only tasks assigned to this role key' },
      from: { type: 'string', description: 'Only tasks delegated by this role key' },
      children: { type: 'string', description: 'Only direct sub-tasks of this task id' },
    },
    examples: ['con agent tasks --open', 'con agent tasks --assigned feeds-tab', 'con agent tasks cancel tsk_abc123'] },

  // search
  { name: 'search', description: 'Cross-service search', safety: 'read',
    args: [{ name: 'query', required: true, description: 'Search query' }],
    flags: { scope: { type: 'string', description: 'Comma-separated: mail,chat,notes,bookmarks,feeds', default: 'mail,chat,notes,bookmarks,feeds' }, limit: { type: 'number', description: 'Max results per service', default: 10 } } },

  // auth
  { name: 'auth login', description: 'Connect an account', safety: 'write',
    args: [{ name: 'provider', required: true, description: 'google or matrix' }],
    flags: { account: { type: 'string', description: 'Account hint' } } },
  { name: 'auth logout', description: 'Disconnect an account', safety: 'destructive',
    args: [{ name: 'provider', required: true, description: 'google or matrix' }],
    flags: { account: { type: 'string', description: 'Account email' } } },
  { name: 'auth status', description: 'Show authentication status', safety: 'read' },
  { name: 'auth accounts', description: 'List all connected accounts', safety: 'read' },

  // money
  { name: 'money status', description: 'Monzo connection status', safety: 'read' },
  { name: 'money accounts', description: 'List Monzo accounts', safety: 'read' },
  { name: 'money balance', description: 'Current account balance', safety: 'read' },
  { name: 'money transactions', description: 'List transactions (cached)', safety: 'read',
    flags: { since: { type: 'string', description: 'ISO date' }, before: { type: 'string', description: 'ISO date' },
      category: { type: 'string', description: 'Monzo category' }, search: { type: 'string', description: 'Search text' },
      limit: { type: 'string', description: 'Max results (default 50)' }, offset: { type: 'string', description: 'Offset' } } },
  { name: 'money get', description: 'Get single transaction detail', safety: 'read',
    args: [{ name: 'tx-id', required: true, description: 'Transaction ID' }] },
  { name: 'money pots', description: 'List pots with balances', safety: 'read' },
  { name: 'money deposit', description: 'Deposit to pot', safety: 'write',
    flags: { pot: { type: 'string', description: 'Pot ID (required)' }, amount: { type: 'string', description: 'Amount in pence (required)' } } },
  { name: 'money withdraw', description: 'Withdraw from pot', safety: 'write',
    flags: { pot: { type: 'string', description: 'Pot ID (required)' }, amount: { type: 'string', description: 'Amount in pence (required)' } } },
  { name: 'money annotate', description: 'Annotate transaction metadata', safety: 'write',
    args: [{ name: 'tx-id', required: true, description: 'Transaction ID' }],
    flags: { key: { type: 'string', description: 'Metadata key (required)' }, value: { type: 'string', description: 'Metadata value' } } },
  { name: 'money spending', description: 'Spending breakdown by category', safety: 'read',
    flags: { month: { type: 'string', description: 'YYYY-MM (default current)' } } },
  { name: 'money sync', description: 'Trigger transaction sync', safety: 'write' },

  // money — financial planner (/finance/*)
  { name: 'money all', description: 'Dump all finance data (categories, rules, accounts, streams, budgets, scenarios, overrides, settings)', safety: 'read' },
  { name: 'money settings', description: 'Get or update planner settings', safety: 'write',
    flags: {
      horizon: { type: 'string', description: 'Projection horizon in months' },
      'investment-growth': { type: 'string', description: 'Annual investment growth %' },
      'emergency-months': { type: 'string', description: 'Emergency fund: months of burn' },
      'emergency-fixed': { type: 'string', description: 'Emergency fund: fixed £' },
    } },
  { name: 'money categories', description: 'List/add/delete categories', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list (default) | add | delete' }],
    flags: { name: { type: 'string', description: '' }, emoji: { type: 'string', description: '' }, color: { type: 'string', description: '' }, kind: { type: 'string', description: 'income|expense|transfer' }, variable: { type: 'string', description: 'true|false' } } },
  { name: 'money rules', description: 'List/add/delete categorisation rules', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | add | delete' }],
    flags: {
      label: { type: 'string', description: '' }, priority: { type: 'string', description: '' },
      category: { type: 'string', description: 'Target category id' },
      merchant: { type: 'string', description: 'Merchant contains' },
      description: { type: 'string', description: 'Description contains' },
      counterparty: { type: 'string', description: 'Counterparty contains' },
      'monzo-cat': { type: 'string', description: 'Monzo category equals' },
      sign: { type: 'string', description: 'in|out' },
      ignore: { type: 'string', description: 'true to mark as ignored' },
      transfer: { type: 'string', description: 'true to mark as transfer' },
    } },
  { name: 'money fin-accounts', description: 'List/add/delete finance accounts', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | add | delete' }],
    flags: { name: { type: 'string', description: '' }, type: { type: 'string', description: 'manual|monzo' }, liquidity: { type: 'string', description: 'liquid|investment|illiquid' }, emoji: { type: 'string', description: '' }, external: { type: 'string', description: 'true if held externally' }, notes: { type: 'string', description: '' }, currency: { type: 'string', description: '' } } },
  { name: 'money fin-balance', description: 'Add a balance entry to a manual account', safety: 'write',
    args: [{ name: 'account-id', required: true, description: 'Account id' }],
    flags: { pounds: { type: 'string', description: 'Balance in £' }, pence: { type: 'string', description: 'Balance in pence' }, date: { type: 'string', description: 'YYYY-MM-DD (default today)' }, note: { type: 'string', description: '' } } },
  { name: 'money streams', description: 'List/add/delete recurring streams', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | add | delete' }],
    flags: { name: { type: 'string', description: '' }, kind: { type: 'string', description: 'income|expense' }, pounds: { type: 'string', description: 'Amount £' }, pence: { type: 'string', description: 'Amount pence' }, cadence: { type: 'string', description: 'monthly|yearly|weekly' }, day: { type: 'string', description: 'Day of month' }, month: { type: 'string', description: 'Month (yearly)' }, start: { type: 'string', description: 'YYYY-MM-DD' }, end: { type: 'string', description: 'YYYY-MM-DD' }, category: { type: 'string', description: 'Category id' }, account: { type: 'string', description: 'Account id' }, growth: { type: 'string', description: 'Annual growth %' }, notes: { type: 'string', description: '' } } },
  { name: 'money budgets', description: 'List/set/delete category budgets', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | set | delete' }],
    flags: { category: { type: 'string', description: 'Category id' }, pounds: { type: 'string', description: 'Monthly target £' }, pence: { type: 'string', description: 'Monthly target pence' }, rollover: { type: 'string', description: 'true|false' } } },
  { name: 'money scenarios', description: 'List/add/delete what-if scenarios', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | add | delete | set-deltas' }],
    flags: { name: { type: 'string', description: '' }, description: { type: 'string', description: '' } },
    examples: ['con money scenarios add --name "Sabbatical 2026"', 'cat deltas.json | con money scenarios set-deltas <id>'] },
  { name: 'money override', description: 'Per-transaction category override', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | set | clear' }],
    flags: { tx: { type: 'string', description: 'Transaction id' }, category: { type: 'string', description: 'Category id' }, ignore: { type: 'string', description: 'true' }, paired: { type: 'string', description: 'Paired tx id (transfer)' } } },
  { name: 'money monthly', description: 'Per-month category aggregation (your categories, not Monzo)', safety: 'read' },
  { name: 'money forecast', description: 'Trailing variable-spend forecast per category', safety: 'read',
    flags: { window: { type: 'string', description: 'Window months (default 3)' } } },
  { name: 'money networth', description: 'Net worth snapshot (or history)', safety: 'read',
    flags: { date: { type: 'string', description: 'Snapshot date (YYYY-MM-DD)' }, history: { type: 'boolean', description: 'Return monthly history instead' }, months: { type: 'string', description: 'History length' } } },
  { name: 'money projection', description: 'Run the projection engine', safety: 'read',
    flags: { horizon: { type: 'string', description: 'Months' }, scenario: { type: 'string', description: 'Scenario id (overlay)' }, window: { type: 'string', description: 'Variable-forecast window' } } },
  { name: 'money runway', description: 'Just the runway summary', safety: 'read',
    flags: { horizon: { type: 'string', description: 'Months' }, scenario: { type: 'string', description: 'Scenario id' } } },
  { name: 'money budget-status', description: 'Actual + projected vs target this month', safety: 'read',
    flags: { month: { type: 'string', description: 'YYYY-MM' } } },
  { name: 'money recurring', description: 'Auto-detected recurring transactions (suggestions for new streams)', safety: 'read' },
  { name: 'money transfers', description: 'Auto-detected transfer pairs between own accounts', safety: 'read' },
  { name: 'money import-csv', description: 'Import a Monzo data export CSV (8+ years of history)', safety: 'write',
    args: [{ name: 'path', required: true, description: 'Path to CSV (use - for stdin)' }],
    flags: { overwrite: { type: 'string', description: 'true to overwrite existing tx' } },
    examples: ['con money import-csv ~/Downloads/MonzoDataExport_*.csv'] },
  { name: 'money detect-accounts', description: 'Scan transactions for outbound flows that look like external accounts (Seccl, Veronica ISA, brokers, etc.)', safety: 'read' },
  { name: 'money apply-candidate', description: 'Create a manual account + ledger from a detect-accounts candidate (JSON on stdin)', safety: 'write',
    examples: ["con money detect-accounts | jq '.[0]' | con money apply-candidate"] },

  // glasses (G1 smart glasses — routed through the phone's APK)
  { name: 'glasses status', description: 'Show glasses connection + battery', safety: 'read',
    examples: ['con glasses status'] },
  { name: 'glasses text', description: 'Write a line of text to the display', safety: 'write',
    args: [{ name: 'text', required: false, description: 'Text to display (or use --text / --stdin)' }],
    flags: { text: { type: 'string', description: 'Text to display' }, stdin: { type: 'boolean', description: 'Read text from stdin' } },
    examples: ['con glasses text "Hello from the terminal"', 'echo "hi" | con glasses text --stdin'] },
  { name: 'glasses clear', description: 'Blank the display (exit current app)', safety: 'write' },
  { name: 'glasses bmp', description: 'Send a 576x136 1-bpp BMP to the display', safety: 'write',
    args: [{ name: 'path', required: true, description: 'Path to the BMP file' }],
    flags: { file: { type: 'string', description: 'Path to the BMP file (alt to positional)' } } },
  { name: 'glasses notify', description: 'Push a notification card to the glasses', safety: 'write',
    flags: { title: { type: 'string', description: 'Notification title (required)' },
             subtitle: { type: 'string', description: 'Subtitle' },
             message: { type: 'string', description: 'Body' },
             app: { type: 'string', description: 'App identifier (default com.console)' } },
    examples: ["con glasses notify --title 'Bus' --message '12 arrives in 3min'"] },
  { name: 'glasses mic', description: 'Start/stop the glasses microphone stream', safety: 'write',
    args: [{ name: 'state', required: true, description: 'on or off' }] },
  { name: 'glasses disconnect', description: 'Temporarily drop BLE link (keeps pairing)', safety: 'write' },
  { name: 'glasses scan', description: 'Trigger BLE scan on phone: start | stop | observations', safety: 'write',
    args: [{ name: 'verb', required: false, description: 'start (default) | stop | observations' }],
    flags: { ms: { type: 'number', description: 'Scan duration in ms (start only)', default: 15000 } },
    examples: ['con glasses scan start', 'con glasses scan observations', 'con glasses scan stop'] },
  { name: 'glasses research', description: 'Reverse-engineering frame log: on|off|tail [N]', safety: 'read',
    args: [{ name: 'verb', required: false, description: 'on | off | tail (default: tail 50)' },
           { name: 'n', required: false, description: 'Line count when verb=tail' }],
    examples: ['con glasses research tail 200', 'con glasses research on', 'con glasses research off'] },
  { name: 'glasses hud', description: 'Toggle the idle head-tilt HUD on|off', safety: 'write',
    args: [{ name: 'state', required: true, description: 'on or off' }],
    examples: ['con glasses hud on', 'con glasses hud off'] },
  { name: 'glasses config', description: 'Show/set HUD + notification config', safety: 'write',
    flags: {
      notify: { type: 'string', description: 'Master notifications toggle: on|off' },
      channel: { type: 'string', description: 'Per-source: --channel <mail|chat|calendar|agent|money> on|off' },
      angle: { type: 'number', description: 'Head-up tilt threshold in degrees (0-60)' },
    },
    examples: ['con glasses config', 'con glasses config --notify off', 'con glasses config --channel money off', 'con glasses config --angle 35'] },

  // pen (Neo smartpen — routed through the phone's APK, like glasses)
  { name: 'pen status', description: 'Show pen connection, battery, storage, lock state', safety: 'read',
    examples: ['con pen status'] },
  { name: 'pen devices', description: 'List bonded/known candidate pens', safety: 'read' },
  { name: 'pen connect', description: 'Connect to a pen (mac optional → last/known)', safety: 'write',
    args: [{ name: 'mac', required: false, description: 'BLE MAC to connect (or use --mac)' }],
    flags: { mac: { type: 'string', description: 'BLE MAC to connect' } },
    examples: ['con pen connect', 'con pen connect AA:BB:CC:DD:EE:FF'] },
  { name: 'pen disconnect', description: 'Drop the BLE link but keep pairing', safety: 'write' },
  { name: 'pen scan', description: 'Trigger BLE scan on phone: start (default) | observations', safety: 'write',
    args: [{ name: 'verb', required: false, description: 'start (default) | observations' }],
    flags: { ms: { type: 'number', description: 'Scan duration in ms (start only)', default: 15000 } },
    examples: ['con pen scan', 'con pen scan observations'] },
  { name: 'pen unlock', description: 'Unlock a password-locked pen', safety: 'write',
    args: [{ name: 'password', required: true, description: 'Pen password (or use --password)' }],
    flags: { password: { type: 'string', description: 'Pen password' } } },
  { name: 'pen research', description: 'Reverse-engineering frame log: on|off|tail [N]', safety: 'read',
    args: [{ name: 'verb', required: false, description: 'on | off | tail (default: tail 50)' },
           { name: 'n', required: false, description: 'Line count when verb=tail' }],
    examples: ['con pen research tail 200', 'con pen research on', 'con pen research off'] },
  { name: 'pen offline', description: 'Rescue stored offline data (non-destructive): notes|pages|pull|files|progress', safety: 'write',
    args: [{ name: 'sub', required: true, description: 'notes | pages | pull | files | progress' },
           { name: 'section', required: false, description: 'Section id (pages/pull)' },
           { name: 'owner', required: false, description: 'Owner id (pages/pull)' },
           { name: 'note', required: false, description: 'Note id (pages/pull)' },
           { name: 'page', required: false, description: 'Page id (pull)' }],
    examples: ['con pen offline notes', 'con pen offline pages 0 27 1', 'con pen offline pull 0 27 1 1', 'con pen offline files'] },

  // whatsapp (absorbed Al runtime — Baileys integration via the hub)
  { name: 'whatsapp status', description: 'WhatsApp connection state + QR readiness', safety: 'read' },
  { name: 'whatsapp qr', description: 'Fetch the current pairing QR PNG (404 when paired or not yet awaiting)', safety: 'read',
    flags: { out: { type: 'string', description: 'Write PNG to this path instead of stdout' } } },
  { name: 'whatsapp send', description: 'Send a WhatsApp message. `to` is a phone (bare or with @s.whatsapp.net) or group/lid JID.', safety: 'write',
    args: [{ name: 'to', required: true, description: 'Phone or JID' }],
    flags: {
      body: { type: 'string', description: 'Message text' },
      file: { type: 'string', description: 'Read body from file' },
      stdin: { type: 'boolean', description: 'Read body from stdin' },
    },
    examples: [
      'con whatsapp send 447700900123 --body "On my way."',
      'cat draft.md | con whatsapp send 447700900123@s.whatsapp.net --stdin',
    ] },
  { name: 'whatsapp delete', description: 'Revoke a message for everyone (~48h window; WhatsApp silently ignores past that)', safety: 'destructive',
    args: [{ name: 'message_id', required: true, description: 'Message id returned by `send`' }],
    flags: { to: { type: 'string', description: 'Recipient JID (required)' } } },
  { name: 'whatsapp contacts', description: 'List workspace contacts (JID lookup; source: ~/.local/share/al/workspace/users/*.md)', safety: 'read',
    flags: { query: { type: 'string', description: 'Filter (substring of username or identifier)' } } },

  // mic — push-to-talk ownership + capture. A single owner session (default
  // Al) receives PTT transcripts; agents can pass the mic to each other.
  { name: 'mic status', description: 'Show the current push-to-talk mic owner + hot state', safety: 'read',
    examples: ['con mic status'] },
  { name: 'mic give', description: 'Give the push-to-talk mic to a session (you become silent listener). Target = session name, id, or agentKey; "al" resets to default.', safety: 'write',
    args: [{ name: 'target', required: true, description: 'Session name | id | agentKey | "al"' }],
    examples: ['con mic give Al', 'con mic give notes-tab', 'con mic give al'] },
  { name: 'mic pass', description: 'Pass the push-to-talk mic to another session — agent-facing alias of `give`. Use your own agentKey to grab it.', safety: 'write',
    args: [{ name: 'target', required: true, description: 'Session name | id | agentKey' }],
    examples: ['con mic pass dashboard-tab', 'con mic pass al'] },
  { name: 'mic release', description: 'Release the mic back to the default owner (Al)', safety: 'write',
    examples: ['con mic release'] },
  { name: 'mic say', description: 'Route a text transcript to the current mic owner and auto-send it', safety: 'write',
    args: [{ name: 'text', required: true, description: 'Text to deliver to the owner session' }],
    examples: ['con mic say "what is on my calendar today"'] },
  { name: 'mic ptt', description: 'Hold-to-talk driver (wired to Sway super+c). `start` records, `stop` transcribes + routes to the owner.', safety: 'write',
    args: [{ name: 'sub', required: true, description: 'start | stop' }],
    examples: ['con mic ptt start', 'con mic ptt stop'] },

  // hub lifecycle
  { name: 'hub restart', description: 'Restart the hub via pm2 (auto-continues in-progress agent sessions)', safety: 'write',
    examples: ['con hub restart'] },

  // dashboard
  { name: 'dashboard status', description: 'Server snapshot (hub, tailscale, pm2, external URLs)', safety: 'read' },
  { name: 'dashboard alerts', description: 'Aggregated alerts: pending agent approvals, upcoming events, recent errors', safety: 'read' },
  { name: 'dashboard servers', description: 'Manage external URL probes shown on the dashboard',
    safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list (default) | add | remove' }],
    flags: {
      name: { type: 'string', description: 'Display name (add)' },
      url: { type: 'string', description: 'URL to probe (add)' },
      'expect-status': { type: 'string', description: 'HTTP status that means healthy (add)' },
    },
    examples: ['con dashboard servers list', 'con dashboard servers add --name vps --url https://example.com', 'con dashboard servers remove srv_abc'] },
  { name: 'dashboard canvas', description: 'Collaborate on the agent canvas via islands or tabs. Islands compose into a grid; tabs are sandboxed sub-canvases owned by one agent each. Falls back to direct index.html writes for full takeover when neither islands nor tabs exist. `publish` mints an unguessable token URL anyone can view without auth.',
    safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list (default) | add | remove | clear | reset | publish | unpublish | url | tab' }],
    flags: {
      title: { type: 'string', description: 'Island header title (add)' },
      by: { type: 'string', description: 'Author tag shown in island header (add). Note: cannot use --agent — it is a global flag.' },
      accent: { type: 'string', description: 'Header accent CSS color (add)' },
      weight: { type: 'string', description: 'Grid column span 1..3 (add)' },
      'expires-in': { type: 'string', description: 'Auto-prune after duration like 30m, 2h, 1d (add)' },
      file: { type: 'string', description: 'Read island HTML from file instead of stdin (add)' },
    },
    examples: [
      'con dashboard canvas list',
      "echo '<h1>Hi</h1>' | con dashboard canvas add greeting --title 'Hello' --by claude",
      'con dashboard canvas add chart --file chart.html --weight 2 --expires-in 1h',
      'con dashboard canvas remove greeting',
      'con dashboard canvas clear',
      'con dashboard canvas reset',
      'con dashboard canvas publish greeting',
      'con dashboard canvas url greeting',
      'con dashboard canvas unpublish greeting',
      'con dashboard canvas tab list',
      "cat slideshow.html | con dashboard canvas tab add flights --title 'Flights' --by claude --accent '#f59e0b'",
      'con dashboard canvas tab publish flights',
      'con dashboard canvas tab url flights',
      'con dashboard canvas tab unpublish flights',
      'con dashboard canvas tab remove flights',
    ] },

  // cron — hub-side scheduler that fires user_prompts into agent sessions.
  // Survives hub restarts (unlike Claude Code's session-scoped /loop / CronCreate).
  { name: 'cron list', description: 'List scheduled tasks (optionally filtered by session)', safety: 'read',
    flags: { session: { type: 'string', description: 'Filter to one claudeSessionId' } },
    examples: ['con cron list', 'con cron list --session 78cf31f5-b0e0-4f2a-8f70-4dc407ed7793'] },
  { name: 'cron add', description: 'Schedule a prompt to fire into a session. Trigger is a 5-field cron, ISO datetime, or relative shorthand (+30m). One-shot if ISO/relative, recurring if cron (override with --once).',
    safety: 'write',
    flags: {
      session: { type: 'string', description: 'REQUIRED. claudeSessionId (UUID) from `con agent list --json`. Hub session ids rejected.' },
      trigger: { type: 'string', description: 'REQUIRED. Cron expression OR ISO datetime OR +30m / +2h / +1d' },
      prompt:  { type: 'string', description: 'REQUIRED. Prompt text sent verbatim into the session on each fire' },
      once:    { type: 'boolean', description: 'Force one-shot even for cron expressions' },
    },
    examples: [
      'con cron add --session $UUID --trigger "*/5 * * * *" --prompt "check CI"',
      'con cron add --session $UUID --trigger "+30m" --prompt "remind me to push the release branch"',
      'con cron add --session $UUID --trigger "2026-05-04T09:00:00" --prompt "stand-up notes"',
    ] },
  { name: 'cron remove', description: 'Delete a scheduled task by id', safety: 'destructive',
    args: [{ name: 'task-id', required: true, description: '8-char id from `con cron list`' }] },
  { name: 'cron run', description: 'Fire a task immediately (does not affect its schedule)', safety: 'write',
    args: [{ name: 'task-id', required: true, description: '8-char id from `con cron list`' }] },
  { name: 'cron upcoming', description: 'Preview the next firings across all tasks', safety: 'read',
    flags: { n: { type: 'string', description: 'Max firings per task (default 20)' } } },
  { name: 'cron ics-url', description: 'Print the calendar subscription URL (token-protected) for the hub schedule', safety: 'read' },

  // blog — drafts, projects, publish for the personal blog (~/sync/brain/root → yousefamar.com/memo)
  { name: 'blog drafts', description: 'List blog drafts in scratch/blog-drafts/', safety: 'read',
    examples: ['con blog drafts'] },
  { name: 'blog draft', description: 'Create a new blog draft (writes a stub with `title`, `post:true`, `public:false`, optional `project`)', safety: 'write',
    args: [{ name: 'title', required: true, description: 'Draft title' }],
    flags: { project: { type: 'string', description: 'Tie to a project by slug' } },
    examples: ['con blog draft "Why I switched to vim"', 'con blog draft "Memo update" --project memo'] },
  { name: 'blog publish', description: 'Publish a draft → log/<timestamp>.md, stamp `date` + `public:true`, hit /rebuild', safety: 'write',
    args: [{ name: 'path', required: true, description: 'Vault-relative draft path (e.g. scratch/blog-drafts/foo.md)' }] },
  { name: 'blog republish', description: 'Re-trigger the Eleventy build for an already-published post (edits go live; no move, date unchanged)', safety: 'write',
    args: [{ name: 'path', required: true, description: 'Published post path (e.g. log/2026-07-09-16-12-35.md)' }] },
  { name: 'blog projects', description: 'List, add, or set status on projects', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list (default) | add | status' }],
    flags: { status: { type: 'string', description: 'Filter by active|dormant|complete (list)' }, slug: { type: 'string', description: 'Slug override (add)' } },
    examples: ['con blog projects', 'con blog projects add "Cura"', 'con blog projects status memo dormant'] },
  { name: 'blog posts', description: 'List posts tagged with a project', safety: 'read',
    args: [{ name: 'slug', required: true, description: 'Project slug' }] },
  { name: 'blog tags', description: 'List all tags used across log/', safety: 'read' },
  { name: 'blog status', description: 'Summary counts: drafts, projects (by status), tags', safety: 'read' },

  // map (Map pane — geocaching.com scraper + offline basemap)
  { name: 'map geocaching status', description: 'Login state, daily request budget, and cached-cache count', safety: 'read' },
  { name: 'map geocaching config', description: 'Set geocaching.com credentials (--username/--password or --cookie <gspkauth>)', safety: 'write',
    args: [{ name: 'flags', required: true, description: '--username --password | --cookie' }] },
  { name: 'map geocaching fetch', description: 'Fetch geocaches in an area (rate-limited): --bbox s,w,n,e or --lat --lon [--radius km] [--max N]', safety: 'write',
    args: [{ name: 'flags', required: true, description: '--bbox | --lat --lon --radius' }] },
  { name: 'map geocaching caches', description: 'List all cached geocaches (summary snapshot)', safety: 'read' },
  { name: 'map geocaching cache', description: 'Full detail (hint, attributes, logs) for one cache; lazy-loaded + cached', safety: 'read',
    args: [{ name: 'gc-code', required: true, description: 'e.g. GC1PAR2' }] },
  { name: 'map meetup status', description: 'Meetup daily request budget + cached-event count + last fetch', safety: 'read' },
  { name: 'map meetup fetch', description: 'Fetch Meetup events near an area (anonymous web GraphQL, rate-limited): --bbox s,w,n,e or --lat --lon [--radius miles] [--query kw] [--days N] [--type physical|online|hybrid] [--pages N]', safety: 'write',
    args: [{ name: 'flags', required: true, description: '--bbox | --lat --lon' }] },
  { name: 'map meetup events', description: 'List all cached Meetup events (summary snapshot, upcoming only)', safety: 'read' },
  { name: 'map meetup event', description: 'Full detail (long description) for one event; lazy-loaded + cached', safety: 'read',
    args: [{ name: 'id', required: true, description: 'Meetup event id' }] },
  { name: 'map layer upsert', description: 'Create/replace a toggle-able GeoJSON map layer (pins/lines/polygons). Style baked into feature props (_color/_size/_icon) + optional --style for polygon fill/popup.', safety: 'write',
    args: [{ name: 'group/name', required: true, description: 'namespaced slug, e.g. where-to-move/towns' }] },
  { name: 'map layer list', description: 'List map layers (index: slug, group, feature count, bbox, style)', safety: 'read' },
  { name: 'map layer get', description: 'Fetch one layer\'s GeoJSON', safety: 'read',
    args: [{ name: 'group/name', required: true, description: 'layer slug' }] },
  { name: 'map layer remove', description: 'Delete one map layer', safety: 'destructive',
    args: [{ name: 'group/name', required: true, description: 'layer slug' }] },
  { name: 'map layer clear', description: 'Delete all map layers, or all under a group prefix', safety: 'destructive',
    args: [{ name: 'group', required: false, description: 'optional group prefix' }] },

  // music (Spotify via hub → spotifyd Connect device; target for media keys)
  { name: 'music now', description: 'Show current Spotify playback (track, position, device)', safety: 'read' },
  { name: 'music status', description: 'Spotify link + spotifyd device status', safety: 'read' },
  { name: 'music play', description: 'No arg: play/pause toggle. With a spotify: URI or free text: play that track. With --playlist/--album/--artist: play that context by name.', safety: 'write',
    args: [{ name: 'query', required: false, description: 'spotify: URI or search text' }],
    flags: { playlist: { type: 'string', description: 'Play a playlist by name' }, album: { type: 'string', description: 'Play an album by name' }, artist: { type: 'string', description: 'Play an artist by name' } } },
  { name: 'music pause', description: 'Pause playback', safety: 'write' },
  { name: 'music next', description: 'Skip to next track', safety: 'write' },
  { name: 'music prev', description: 'Skip to previous track', safety: 'write' },
  { name: 'music vol', description: 'Set volume: 0-100, or relative +N / -N', safety: 'write',
    args: [{ name: 'level', required: true, description: '0-100 | +N | -N' }] },
  { name: 'music seek', description: 'Seek: absolute seconds, or relative +N / -N', safety: 'write',
    args: [{ name: 'seconds', required: true, description: 'seconds | +N | -N' }] },
  { name: 'music shuffle', description: 'Shuffle on | off | toggle', safety: 'write',
    args: [{ name: 'state', required: false, description: 'on | off (default toggle)' }] },
  { name: 'music repeat', description: 'Repeat off | context | track | cycle', safety: 'write',
    args: [{ name: 'state', required: false, description: 'off | context | track (default cycle)' }] },
  { name: 'music devices', description: 'List available Spotify Connect devices', safety: 'read' },
  { name: 'music transfer', description: 'Transfer playback to a device (by name or id)', safety: 'write',
    args: [{ name: 'device', required: true, description: 'device name or id' }] },
  { name: 'music search', description: 'Search Spotify tracks', safety: 'read',
    args: [{ name: 'query', required: true, description: 'search text' }] },
  { name: 'music queue', description: 'Add a track to the queue (uri or search text)', safety: 'write',
    args: [{ name: 'query', required: true, description: 'spotify: URI or search text' }] },
  { name: 'music playlists', description: 'List your Spotify playlists', safety: 'read' },
  { name: 'music liked', description: 'Play your Liked Songs', safety: 'write' },
  { name: 'music add', description: 'Add a track to a playlist (track defaults to now-playing)', safety: 'write',
    args: [{ name: 'playlist', required: true, description: 'playlist name or spotify: URI' }, { name: 'track', required: false, description: 'track query or URI (default: current)' }] },
  { name: 'music remove', description: 'Remove a track from a playlist (track defaults to now-playing)', safety: 'destructive',
    args: [{ name: 'playlist', required: true, description: 'playlist name or spotify: URI' }, { name: 'track', required: false, description: 'track query or URI (default: current)' }] },
  { name: 'music like', description: 'Save the current track to Liked Songs', safety: 'write' },
  { name: 'music unlike', description: 'Remove the current track from your library', safety: 'write' },

  // system
  { name: 'status', description: 'Hub health and sync status', safety: 'read' },
  { name: 'capabilities', description: 'List all commands for agent discovery', safety: 'read' },
  { name: 'schema', description: 'JSONSchema for any command', safety: 'read',
    args: [{ name: 'command', required: false, description: 'Command name (e.g. mail.list)' }] },
  { name: 'version', description: 'Show CLI version', safety: 'read' },
]

// Service aliases
export const ALIASES: Record<string, string> = {
  m: 'mail',
  c: 'chat',
  b: 'bookmarks',
  n: 'notes',
  f: 'feeds',
  a: 'agent',
  s: 'search',
  mo: 'money',
}
