// Command registry — source of truth for capabilities and schema introspection

export interface CommandDef {
  name: string
  description: string
  safety: 'read' | 'write' | 'destructive'
  args?: Array<{ name: string; required: boolean; description: string }>
  flags?: Record<string, {
    type: 'string' | 'number' | 'boolean'
    alias?: string
    description: string
    default?: unknown
  }>
  examples?: string[]
}

export const COMMANDS: CommandDef[] = [
  // mail
  { name: 'mail list', description: 'List inbox threads', safety: 'read',
    flags: { query: { type: 'string', alias: 'q', description: 'Gmail search query', default: 'in:inbox' }, max: { type: 'number', description: 'Max results', default: 50 }, 'page-token': { type: 'string', description: 'Pagination token' } },
    examples: ['con mail list', "con mail list --query 'from:alice is:unread' --max 10"] },
  { name: 'mail read', description: 'Read a thread with messages', safety: 'read',
    args: [{ name: 'thread-id', required: true, description: 'Gmail thread ID' }],
    flags: { format: { type: 'string', description: 'Output format', default: 'plain' } } },
  { name: 'mail archive', description: 'Archive thread(s)', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail trash', description: 'Move thread(s) to trash', safety: 'destructive',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail snooze', description: 'Snooze a thread until later', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }],
    flags: { until: { type: 'string', description: 'Snooze until: later-today, tomorrow, next-week, monday, or ISO date' } } },
  { name: 'mail unsnooze', description: 'Unsnooze a thread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }] },
  { name: 'mail mark-read', description: 'Mark thread(s) as read', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail mark-unread', description: 'Mark thread(s) as unread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID(s)' }] },
  { name: 'mail reply', description: 'Reply to a thread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }],
    flags: { body: { type: 'string', description: 'Reply body text' }, html: { type: 'boolean', description: 'Body is HTML' }, 'reply-all': { type: 'boolean', description: 'Reply to all recipients' }, cc: { type: 'string', description: 'CC address(es)' } } },
  { name: 'mail forward', description: 'Forward a thread', safety: 'write',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }],
    flags: { to: { type: 'string', description: 'Recipient' }, body: { type: 'string', description: 'Additional body text' } } },
  { name: 'mail send', description: 'Send a new email', safety: 'write',
    flags: { to: { type: 'string', description: 'Recipient' }, subject: { type: 'string', description: 'Subject' }, body: { type: 'string', description: 'Body text' }, cc: { type: 'string', description: 'CC address' }, from: { type: 'string', description: 'From alias' }, html: { type: 'boolean', description: 'Body is HTML' }, attach: { type: 'string', description: 'File path(s) to attach' } },
    examples: ["con mail send --to alice@example.com --subject 'Hello' --body 'Hi there'"] },
  { name: 'mail attachments', description: 'List attachments for a thread', safety: 'read',
    args: [{ name: 'thread-id', required: true, description: 'Thread ID' }] },
  { name: 'mail download', description: 'Download an attachment', safety: 'read',
    args: [{ name: 'message-id', required: true, description: 'Message ID' }, { name: 'attachment-id', required: true, description: 'Attachment ID' }],
    flags: { out: { type: 'string', description: 'Output file path' } } },
  { name: 'mail contacts', description: 'Search contacts', safety: 'read',
    args: [{ name: 'query', required: true, description: 'Search query' }] },
  { name: 'mail aliases', description: 'List send-as aliases', safety: 'read' },
  { name: 'mail undo', description: 'Undo last archive/trash', safety: 'write' },

  // chat
  { name: 'chat rooms', description: 'List chat rooms', safety: 'read',
    flags: { filter: { type: 'string', description: 'Filter: unread, all, favourites, snoozed', default: 'unread' } } },
  { name: 'chat messages', description: 'Read messages in a room', safety: 'read',
    args: [{ name: 'room-id', required: true, description: 'Matrix room ID' }],
    flags: { limit: { type: 'number', description: 'Max messages', default: 50 }, before: { type: 'string', description: 'Pagination token' } } },
  { name: 'chat send', description: 'Send a message to a room', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Matrix room ID' }],
    flags: { body: { type: 'string', description: 'Message text' }, html: { type: 'boolean', description: 'Body is HTML' }, 'reply-to': { type: 'string', description: 'Event ID to reply to' } } },
  { name: 'chat send-file', description: 'Send a file to a room', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }, { name: 'file-path', required: true, description: 'File to send' }],
    flags: { caption: { type: 'string', description: 'Caption text' } } },
  { name: 'chat react', description: 'React to a message', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }, { name: 'event-id', required: true, description: 'Event ID' }, { name: 'emoji', required: true, description: 'Emoji reaction' }] },
  { name: 'chat mark-read', description: 'Mark room(s) as read', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID(s)' }] },
  { name: 'chat mark-unread', description: 'Mark a room as unread', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }] },
  { name: 'chat snooze', description: 'Snooze a room', safety: 'write',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }],
    flags: { until: { type: 'string', description: 'Snooze until' } } },
  { name: 'chat info', description: 'Get room details', safety: 'read',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }] },
  { name: 'chat tail', description: 'Stream new messages (NDJSON)', safety: 'read',
    args: [{ name: 'room-id', required: true, description: 'Room ID' }] },
  { name: 'chat undo', description: 'Undo last mark-read', safety: 'write' },

  // bookmarks
  { name: 'bookmarks list', description: 'List bookmarks', safety: 'read',
    flags: { tag: { type: 'string', description: 'Filter by tag' }, search: { type: 'string', alias: 'q', description: 'Search query' }, limit: { type: 'number', description: 'Max results' } },
    examples: ['con bookmarks list', "con bookmarks list --tag dev/frontend --search react"] },
  { name: 'bookmarks get', description: 'Get bookmark details', safety: 'read',
    args: [{ name: 'filename', required: true, description: 'Bookmark filename (e.g. my-bookmark.md)' }] },
  { name: 'bookmarks tags', description: 'List all tags with counts', safety: 'read' },
  { name: 'bookmarks update', description: 'Update bookmark tags/title', safety: 'write',
    args: [{ name: 'filename', required: true, description: 'Bookmark filename' }],
    flags: { 'add-tag': { type: 'string', description: 'Tag(s) to add' }, 'remove-tag': { type: 'string', description: 'Tag(s) to remove' }, title: { type: 'string', description: 'New title' } } },
  { name: 'bookmarks delete', description: 'Delete a bookmark', safety: 'destructive',
    args: [{ name: 'filename', required: true, description: 'Bookmark filename' }] },
  { name: 'bookmarks reload', description: 'Force reload from disk', safety: 'read' },

  // notes
  { name: 'notes list', description: 'List vault files', safety: 'read',
    flags: { dir: { type: 'string', description: 'Subdirectory to list' } },
    examples: ['con notes list', 'con notes list --dir scratch'] },
  { name: 'notes read', description: 'Read a note', safety: 'read',
    args: [{ name: 'path', required: true, description: 'File path relative to vault root' }] },
  { name: 'notes write', description: 'Write/create a note', safety: 'write',
    args: [{ name: 'path', required: true, description: 'File path' }],
    flags: { content: { type: 'string', description: 'File content' }, stdin: { type: 'boolean', description: 'Read content from stdin' } } },
  { name: 'notes append', description: 'Append to a note', safety: 'write',
    args: [{ name: 'path', required: true, description: 'File path' }],
    flags: { content: { type: 'string', description: 'Content to append' } } },
  { name: 'notes delete', description: 'Delete a note', safety: 'destructive',
    args: [{ name: 'path', required: true, description: 'File path' }] },
  { name: 'notes rename', description: 'Rename/move a note', safety: 'write',
    args: [{ name: 'from', required: true, description: 'Current path' }, { name: 'to', required: true, description: 'New path' }] },
  { name: 'notes mkdir', description: 'Create a directory', safety: 'write',
    args: [{ name: 'path', required: true, description: 'Directory path' }] },
  { name: 'notes search', description: 'Search notes', safety: 'read',
    args: [{ name: 'query', required: true, description: 'Search query' }],
    flags: { mode: { type: 'string', description: 'Search mode: filename or content', default: 'filename' } } },
  { name: 'notes daily', description: 'Read or append to daily note', safety: 'write',
    flags: { content: { type: 'string', description: 'Content to append (omit to read)' } } },

  // feeds
  { name: 'feeds list', description: 'List feed subscriptions', safety: 'read',
    flags: { folder: { type: 'string', description: 'Filter by folder' } } },
  { name: 'feeds items', description: 'List feed items', safety: 'read',
    flags: { feed: { type: 'string', description: 'Filter by feed ID' }, folder: { type: 'string', description: 'Filter by folder' }, unread: { type: 'boolean', description: 'Show unread only' }, since: { type: 'string', description: 'Items since date (ISO)' }, limit: { type: 'number', description: 'Max results', default: 50 } } },
  { name: 'feeds read', description: 'Read a feed item', safety: 'read',
    args: [{ name: 'item-id', required: true, description: 'Feed item ID' }] },
  { name: 'feeds mark-read', description: 'Mark items as read', safety: 'write',
    flags: { item: { type: 'string', description: 'Item ID' }, feed: { type: 'string', description: 'Feed ID (mark all in feed)' }, folder: { type: 'string', description: 'Folder (mark all in folder)' }, all: { type: 'boolean', description: 'Mark everything read' } } },
  { name: 'feeds mark-unread', description: 'Mark an item as unread', safety: 'write',
    args: [{ name: 'item-id', required: true, description: 'Item ID' }] },
  { name: 'feeds add', description: 'Subscribe to a feed', safety: 'write',
    args: [{ name: 'url', required: true, description: 'Feed URL' }],
    flags: { title: { type: 'string', description: 'Feed title' }, folder: { type: 'string', description: 'Folder name' }, 'full-text': { type: 'boolean', description: 'Fetch full article text' } } },
  { name: 'feeds delete', description: 'Unsubscribe from a feed', safety: 'destructive',
    args: [{ name: 'feed-id', required: true, description: 'Feed ID' }] },
  { name: 'feeds import', description: 'Import feeds from OPML', safety: 'write',
    args: [{ name: 'opml-file', required: true, description: 'Path to OPML file' }] },
  { name: 'feeds export', description: 'Export feeds as OPML', safety: 'read',
    flags: { out: { type: 'string', description: 'Output file path' } } },

  // cal
  { name: 'cal calendars', description: 'List calendars', safety: 'read',
    flags: { account: { type: 'string', description: 'Filter by account email' } } },
  { name: 'cal events', description: 'List events', safety: 'read',
    flags: { from: { type: 'string', description: 'Start date' }, to: { type: 'string', description: 'End date' }, calendar: { type: 'string', description: 'Calendar ID' }, account: { type: 'string', description: 'Account email' } },
    examples: ['con cal events --from today --to +7d'] },
  { name: 'cal get', description: 'Get event details', safety: 'read',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal create', description: 'Create an event', safety: 'write',
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, title: { type: 'string', description: 'Event title' }, start: { type: 'string', description: 'Start datetime' }, end: { type: 'string', description: 'End datetime' }, account: { type: 'string', description: 'Account email' }, description: { type: 'string', description: 'Description' }, location: { type: 'string', description: 'Location' }, 'all-day': { type: 'boolean', description: 'All-day event' } } },
  { name: 'cal edit', description: 'Edit an event', safety: 'write',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, title: { type: 'string', description: 'New title' }, start: { type: 'string', description: 'New start' }, end: { type: 'string', description: 'New end' }, account: { type: 'string', description: 'Account email' }, 'this-only': { type: 'boolean', description: 'Edit only this instance' }, 'all-events': { type: 'boolean', description: 'Edit all instances' } } },
  { name: 'cal delete', description: 'Delete an event', safety: 'destructive',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal rsvp', description: 'RSVP to an event', safety: 'write',
    args: [{ name: 'event-id', required: true, description: 'Event ID' }],
    flags: { calendar: { type: 'string', description: 'Calendar ID' }, status: { type: 'string', description: 'accept, maybe, or decline' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal location', description: 'Set working location', safety: 'write',
    flags: { date: { type: 'string', description: 'Date' }, type: { type: 'string', description: 'home, office, or custom' }, label: { type: 'string', description: 'Custom location label' }, account: { type: 'string', description: 'Account email' } } },
  { name: 'cal accounts', description: 'List calendar accounts', safety: 'read' },
  { name: 'cal add-account', description: 'Add a calendar account', safety: 'write' },
  { name: 'cal remove-account', description: 'Remove a calendar account', safety: 'destructive',
    args: [{ name: 'email', required: true, description: 'Account email' }] },

  // agent
  { name: 'agent list', description: 'List agent sessions', safety: 'read',
    flags: { past: { type: 'boolean', description: 'Include past sessions' }, cwd: { type: 'string', description: 'Working directory' } } },
  { name: 'agent create', description: 'Create a new agent session', safety: 'write',
    args: [{ name: 'prompt', required: true, description: 'Initial prompt' }],
    flags: { cwd: { type: 'string', description: 'Working directory' }, wait: { type: 'boolean', description: 'Block until complete' } } },
  { name: 'agent send', description: 'Send a message to a session', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }, { name: 'message', required: true, description: 'Message text' }] },
  { name: 'agent resume', description: 'Resume a past session', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }],
    flags: { prompt: { type: 'string', description: 'Resume prompt' }, cwd: { type: 'string', description: 'Working directory' } } },
  { name: 'agent kill', description: 'Kill a session', safety: 'destructive',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },
  { name: 'agent interrupt', description: 'Interrupt a session', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },
  { name: 'agent approve', description: 'Approve tool use', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }, { name: 'request-id', required: true, description: 'Request ID' }],
    flags: { input: { type: 'string', description: 'Modified input JSON' } } },
  { name: 'agent deny', description: 'Deny tool use', safety: 'write',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }, { name: 'request-id', required: true, description: 'Request ID' }],
    flags: { reason: { type: 'string', description: 'Denial reason' } } },
  { name: 'agent tail', description: 'Stream session output (NDJSON)', safety: 'read',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },
  { name: 'agent wait', description: 'Block until session completes', safety: 'read',
    args: [{ name: 'session-id', required: true, description: 'Session ID' }] },

  // search
  { name: 'search', description: 'Cross-service search', safety: 'read',
    args: [{ name: 'query', required: true, description: 'Search query' }],
    flags: { scope: { type: 'string', description: 'Comma-separated: mail,chat,notes,bookmarks,feeds', default: 'mail,chat,notes,bookmarks,feeds' }, limit: { type: 'number', description: 'Max results per service', default: 10 } } },

  // auth
  { name: 'auth login', description: 'Connect an account', safety: 'write',
    args: [{ name: 'provider', required: true, description: 'google or matrix' }],
    flags: { account: { type: 'string', description: 'Account hint' } } },
  { name: 'auth logout', description: 'Disconnect an account', safety: 'destructive',
    args: [{ name: 'provider', required: true, description: 'google or matrix' }],
    flags: { account: { type: 'string', description: 'Account email' } } },
  { name: 'auth status', description: 'Show authentication status', safety: 'read' },
  { name: 'auth accounts', description: 'List all connected accounts', safety: 'read' },

  // money
  { name: 'money status', description: 'Monzo connection status', safety: 'read' },
  { name: 'money accounts', description: 'List Monzo accounts', safety: 'read' },
  { name: 'money balance', description: 'Current account balance', safety: 'read' },
  { name: 'money transactions', description: 'List transactions (cached)', safety: 'read',
    flags: { since: { type: 'string', description: 'ISO date' }, before: { type: 'string', description: 'ISO date' },
      category: { type: 'string', description: 'Monzo category' }, search: { type: 'string', description: 'Search text' },
      limit: { type: 'string', description: 'Max results (default 50)' }, offset: { type: 'string', description: 'Offset' } } },
  { name: 'money get', description: 'Get single transaction detail', safety: 'read',
    args: [{ name: 'tx-id', required: true, description: 'Transaction ID' }] },
  { name: 'money pots', description: 'List pots with balances', safety: 'read' },
  { name: 'money deposit', description: 'Deposit to pot', safety: 'write',
    flags: { pot: { type: 'string', description: 'Pot ID (required)' }, amount: { type: 'string', description: 'Amount in pence (required)' } } },
  { name: 'money withdraw', description: 'Withdraw from pot', safety: 'write',
    flags: { pot: { type: 'string', description: 'Pot ID (required)' }, amount: { type: 'string', description: 'Amount in pence (required)' } } },
  { name: 'money annotate', description: 'Annotate transaction metadata', safety: 'write',
    args: [{ name: 'tx-id', required: true, description: 'Transaction ID' }],
    flags: { key: { type: 'string', description: 'Metadata key (required)' }, value: { type: 'string', description: 'Metadata value' } } },
  { name: 'money spending', description: 'Spending breakdown by category', safety: 'read',
    flags: { month: { type: 'string', description: 'YYYY-MM (default current)' } } },
  { name: 'money sync', description: 'Trigger transaction sync', safety: 'write' },

  // money — financial planner (/finance/*)
  { name: 'money all', description: 'Dump all finance data (categories, rules, accounts, streams, budgets, scenarios, overrides, settings)', safety: 'read' },
  { name: 'money settings', description: 'Get or update planner settings', safety: 'write',
    flags: {
      horizon: { type: 'string', description: 'Projection horizon in months' },
      'investment-growth': { type: 'string', description: 'Annual investment growth %' },
      'emergency-months': { type: 'string', description: 'Emergency fund: months of burn' },
      'emergency-fixed': { type: 'string', description: 'Emergency fund: fixed £' },
    } },
  { name: 'money categories', description: 'List/add/delete categories', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list (default) | add | delete' }],
    flags: { name: { type: 'string', description: '' }, emoji: { type: 'string', description: '' }, color: { type: 'string', description: '' }, kind: { type: 'string', description: 'income|expense|transfer' }, variable: { type: 'string', description: 'true|false' } } },
  { name: 'money rules', description: 'List/add/delete categorisation rules', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | add | delete' }],
    flags: {
      label: { type: 'string', description: '' }, priority: { type: 'string', description: '' },
      category: { type: 'string', description: 'Target category id' },
      merchant: { type: 'string', description: 'Merchant contains' },
      description: { type: 'string', description: 'Description contains' },
      counterparty: { type: 'string', description: 'Counterparty contains' },
      'monzo-cat': { type: 'string', description: 'Monzo category equals' },
      sign: { type: 'string', description: 'in|out' },
      ignore: { type: 'string', description: 'true to mark as ignored' },
      transfer: { type: 'string', description: 'true to mark as transfer' },
    } },
  { name: 'money fin-accounts', description: 'List/add/delete finance accounts', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | add | delete' }],
    flags: { name: { type: 'string', description: '' }, type: { type: 'string', description: 'manual|monzo' }, liquidity: { type: 'string', description: 'liquid|investment|illiquid' }, emoji: { type: 'string', description: '' }, external: { type: 'string', description: 'true if held externally' }, notes: { type: 'string', description: '' }, currency: { type: 'string', description: '' } } },
  { name: 'money fin-balance', description: 'Add a balance entry to a manual account', safety: 'write',
    args: [{ name: 'account-id', required: true, description: 'Account id' }],
    flags: { pounds: { type: 'string', description: 'Balance in £' }, pence: { type: 'string', description: 'Balance in pence' }, date: { type: 'string', description: 'YYYY-MM-DD (default today)' }, note: { type: 'string', description: '' } } },
  { name: 'money streams', description: 'List/add/delete recurring streams', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | add | delete' }],
    flags: { name: { type: 'string', description: '' }, kind: { type: 'string', description: 'income|expense' }, pounds: { type: 'string', description: 'Amount £' }, pence: { type: 'string', description: 'Amount pence' }, cadence: { type: 'string', description: 'monthly|yearly|weekly' }, day: { type: 'string', description: 'Day of month' }, month: { type: 'string', description: 'Month (yearly)' }, start: { type: 'string', description: 'YYYY-MM-DD' }, end: { type: 'string', description: 'YYYY-MM-DD' }, category: { type: 'string', description: 'Category id' }, account: { type: 'string', description: 'Account id' }, growth: { type: 'string', description: 'Annual growth %' }, notes: { type: 'string', description: '' } } },
  { name: 'money budgets', description: 'List/set/delete category budgets', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | set | delete' }],
    flags: { category: { type: 'string', description: 'Category id' }, pounds: { type: 'string', description: 'Monthly target £' }, pence: { type: 'string', description: 'Monthly target pence' }, rollover: { type: 'string', description: 'true|false' } } },
  { name: 'money scenarios', description: 'List/add/delete what-if scenarios', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | add | delete | set-deltas' }],
    flags: { name: { type: 'string', description: '' }, description: { type: 'string', description: '' } },
    examples: ['con money scenarios add --name "Sabbatical 2026"', 'cat deltas.json | con money scenarios set-deltas <id>'] },
  { name: 'money override', description: 'Per-transaction category override', safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list | set | clear' }],
    flags: { tx: { type: 'string', description: 'Transaction id' }, category: { type: 'string', description: 'Category id' }, ignore: { type: 'string', description: 'true' }, paired: { type: 'string', description: 'Paired tx id (transfer)' } } },
  { name: 'money monthly', description: 'Per-month category aggregation (your categories, not Monzo)', safety: 'read' },
  { name: 'money forecast', description: 'Trailing variable-spend forecast per category', safety: 'read',
    flags: { window: { type: 'string', description: 'Window months (default 3)' } } },
  { name: 'money networth', description: 'Net worth snapshot (or history)', safety: 'read',
    flags: { date: { type: 'string', description: 'Snapshot date (YYYY-MM-DD)' }, history: { type: 'boolean', description: 'Return monthly history instead' }, months: { type: 'string', description: 'History length' } } },
  { name: 'money projection', description: 'Run the projection engine', safety: 'read',
    flags: { horizon: { type: 'string', description: 'Months' }, scenario: { type: 'string', description: 'Scenario id (overlay)' }, window: { type: 'string', description: 'Variable-forecast window' } } },
  { name: 'money runway', description: 'Just the runway summary', safety: 'read',
    flags: { horizon: { type: 'string', description: 'Months' }, scenario: { type: 'string', description: 'Scenario id' } } },
  { name: 'money budget-status', description: 'Actual + projected vs target this month', safety: 'read',
    flags: { month: { type: 'string', description: 'YYYY-MM' } } },
  { name: 'money recurring', description: 'Auto-detected recurring transactions (suggestions for new streams)', safety: 'read' },
  { name: 'money transfers', description: 'Auto-detected transfer pairs between own accounts', safety: 'read' },
  { name: 'money import-csv', description: 'Import a Monzo data export CSV (8+ years of history)', safety: 'write',
    args: [{ name: 'path', required: true, description: 'Path to CSV (use - for stdin)' }],
    flags: { overwrite: { type: 'string', description: 'true to overwrite existing tx' } },
    examples: ['con money import-csv ~/Downloads/MonzoDataExport_*.csv'] },
  { name: 'money detect-accounts', description: 'Scan transactions for outbound flows that look like external accounts (Seccl, Veronica ISA, brokers, etc.)', safety: 'read' },
  { name: 'money apply-candidate', description: 'Create a manual account + ledger from a detect-accounts candidate (JSON on stdin)', safety: 'write',
    examples: ["con money detect-accounts | jq '.[0]' | con money apply-candidate"] },

  // glasses (G1 smart glasses — routed through the phone's APK)
  { name: 'glasses status', description: 'Show glasses connection + battery', safety: 'read',
    examples: ['con glasses status'] },
  { name: 'glasses text', description: 'Write a line of text to the display', safety: 'write',
    args: [{ name: 'text', required: false, description: 'Text to display (or use --text / --stdin)' }],
    flags: { text: { type: 'string', description: 'Text to display' }, stdin: { type: 'boolean', description: 'Read text from stdin' } },
    examples: ['con glasses text "Hello from the terminal"', 'echo "hi" | con glasses text --stdin'] },
  { name: 'glasses clear', description: 'Blank the display (exit current app)', safety: 'write' },
  { name: 'glasses bmp', description: 'Send a 576x136 1-bpp BMP to the display', safety: 'write',
    args: [{ name: 'path', required: true, description: 'Path to the BMP file' }],
    flags: { file: { type: 'string', description: 'Path to the BMP file (alt to positional)' } } },
  { name: 'glasses notify', description: 'Push a notification card to the glasses', safety: 'write',
    flags: { title: { type: 'string', description: 'Notification title (required)' },
             subtitle: { type: 'string', description: 'Subtitle' },
             message: { type: 'string', description: 'Body' },
             app: { type: 'string', description: 'App identifier (default com.console)' } },
    examples: ["con glasses notify --title 'Bus' --message '12 arrives in 3min'"] },
  { name: 'glasses mic', description: 'Start/stop the glasses microphone stream', safety: 'write',
    args: [{ name: 'state', required: true, description: 'on or off' }] },
  { name: 'glasses disconnect', description: 'Temporarily drop BLE link (keeps pairing)', safety: 'write' },
  { name: 'glasses scan', description: 'Trigger BLE scan on phone: start | stop | observations', safety: 'write',
    args: [{ name: 'verb', required: false, description: 'start (default) | stop | observations' }],
    flags: { ms: { type: 'number', description: 'Scan duration in ms (start only)', default: 15000 } },
    examples: ['con glasses scan start', 'con glasses scan observations', 'con glasses scan stop'] },
  { name: 'glasses research', description: 'Reverse-engineering frame log: on|off|tail [N]', safety: 'read',
    args: [{ name: 'verb', required: false, description: 'on | off | tail (default: tail 50)' },
           { name: 'n', required: false, description: 'Line count when verb=tail' }],
    examples: ['con glasses research tail 200', 'con glasses research on', 'con glasses research off'] },

  // hub lifecycle
  { name: 'hub restart', description: 'Restart the hub via pm2 (auto-continues in-progress agent sessions)', safety: 'write',
    examples: ['con hub restart'] },

  // dashboard
  { name: 'dashboard status', description: 'Server snapshot (hub, tailscale, pm2, external URLs)', safety: 'read' },
  { name: 'dashboard alerts', description: 'Aggregated alerts: pending agent approvals, upcoming events, recent errors', safety: 'read' },
  { name: 'dashboard servers', description: 'Manage external URL probes shown on the dashboard',
    safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list (default) | add | remove' }],
    flags: {
      name: { type: 'string', description: 'Display name (add)' },
      url: { type: 'string', description: 'URL to probe (add)' },
      'expect-status': { type: 'string', description: 'HTTP status that means healthy (add)' },
    },
    examples: ['con dashboard servers list', 'con dashboard servers add --name vps --url https://example.com', 'con dashboard servers remove srv_abc'] },
  { name: 'dashboard canvas', description: 'Collaborate on the agent canvas via islands. Multiple agents can each own a slug; hub composes them into a grid. Falls back to direct index.html writes for full takeover.',
    safety: 'write',
    args: [{ name: 'sub', required: false, description: 'list (default) | add | remove | clear | reset' }],
    flags: {
      title: { type: 'string', description: 'Island header title (add)' },
      by: { type: 'string', description: 'Author tag shown in island header (add). Note: cannot use --agent — it is a global flag.' },
      accent: { type: 'string', description: 'Header accent CSS color (add)' },
      weight: { type: 'string', description: 'Grid column span 1..3 (add)' },
      'expires-in': { type: 'string', description: 'Auto-prune after duration like 30m, 2h, 1d (add)' },
      file: { type: 'string', description: 'Read island HTML from file instead of stdin (add)' },
    },
    examples: [
      'con dashboard canvas list',
      "echo '<h1>Hi</h1>' | con dashboard canvas add greeting --title 'Hello' --by claude",
      'con dashboard canvas add chart --file chart.html --weight 2 --expires-in 1h',
      'con dashboard canvas remove greeting',
      'con dashboard canvas clear',
      'con dashboard canvas reset',
    ] },

  // cron — hub-side scheduler that fires user_prompts into agent sessions.
  // Survives hub restarts (unlike Claude Code's session-scoped /loop / CronCreate).
  { name: 'cron list', description: 'List scheduled tasks (optionally filtered by session)', safety: 'read',
    flags: { session: { type: 'string', description: 'Filter to one claudeSessionId' } },
    examples: ['con cron list', 'con cron list --session 78cf31f5-b0e0-4f2a-8f70-4dc407ed7793'] },
  { name: 'cron add', description: 'Schedule a prompt to fire into a session. Trigger is a 5-field cron, ISO datetime, or relative shorthand (+30m). One-shot if ISO/relative, recurring if cron (override with --once).',
    safety: 'write',
    flags: {
      session: { type: 'string', description: 'REQUIRED. claudeSessionId (UUID) from `con agent list --json`. Hub session ids rejected.' },
      trigger: { type: 'string', description: 'REQUIRED. Cron expression OR ISO datetime OR +30m / +2h / +1d' },
      prompt:  { type: 'string', description: 'REQUIRED. Prompt text sent verbatim into the session on each fire' },
      once:    { type: 'boolean', description: 'Force one-shot even for cron expressions' },
    },
    examples: [
      'con cron add --session $UUID --trigger "*/5 * * * *" --prompt "check CI"',
      'con cron add --session $UUID --trigger "+30m" --prompt "remind me to push the release branch"',
      'con cron add --session $UUID --trigger "2026-05-04T09:00:00" --prompt "stand-up notes"',
    ] },
  { name: 'cron remove', description: 'Delete a scheduled task by id', safety: 'destructive',
    args: [{ name: 'task-id', required: true, description: '8-char id from `con cron list`' }] },
  { name: 'cron run', description: 'Fire a task immediately (does not affect its schedule)', safety: 'write',
    args: [{ name: 'task-id', required: true, description: '8-char id from `con cron list`' }] },
  { name: 'cron upcoming', description: 'Preview the next firings across all tasks', safety: 'read',
    flags: { n: { type: 'string', description: 'Max firings per task (default 20)' } } },
  { name: 'cron ics-url', description: 'Print the calendar subscription URL (token-protected) for the hub schedule', safety: 'read' },

  // system
  { name: 'status', description: 'Hub health and sync status', safety: 'read' },
  { name: 'capabilities', description: 'List all commands for agent discovery', safety: 'read' },
  { name: 'schema', description: 'JSONSchema for any command', safety: 'read',
    args: [{ name: 'command', required: false, description: 'Command name (e.g. mail.list)' }] },
  { name: 'version', description: 'Show CLI version', safety: 'read' },
]

// Service aliases
export const ALIASES: Record<string, string> = {
  m: 'mail',
  c: 'chat',
  b: 'bookmarks',
  n: 'notes',
  f: 'feeds',
  a: 'agent',
  s: 'search',
  mo: 'money',
}
