import {
  initAsync,
  OlmMachine,
  UserId,
  DeviceId,
  RoomId,
  DeviceLists,
  RequestType,
  DecryptionSettings,
  TrustRequirement,
  EncryptionSettings,
  type KeysUploadRequest,
  type KeysQueryRequest,
  type KeysClaimRequest,
  type ToDeviceRequest,
  type SignatureUploadRequest,
  type KeysBackupRequest,
  type OutgoingRequest,
} from '@matrix-org/matrix-sdk-crypto-wasm'
import { getMatrixAccessToken, getMatrixHomeserver, getMatrixUserId } from './auth'
import type { MatrixSyncResponse, MatrixEvent } from './types'

let machine: OlmMachine | null = null
let initialized = false

// --- Init ---

const CRYPTO_STORE = 'console-crypto-store'
const CRYPTO_DEVICE_KEY = 'console-crypto-device-id'

function deleteDb(name: string): Promise<void> {
  return new Promise((resolve) => {
    const req = indexedDB.deleteDatabase(name)
    req.onsuccess = () => resolve()
    req.onerror = () => resolve()
    req.onblocked = () => resolve()
  })
}

export async function initCrypto(userId: string, deviceId: string, force = false): Promise<void> {
  if (initialized && !force) return

  // If device ID changed since last init, wipe the stale crypto store
  // before OlmMachine tries to open it (avoids blocked deleteDatabase)
  const storedDeviceId = localStorage.getItem(CRYPTO_DEVICE_KEY)
  if (storedDeviceId && storedDeviceId !== deviceId) {
    console.warn('[crypto] Device ID changed from', storedDeviceId, 'to', deviceId, '— clearing crypto store')
    await deleteDb(CRYPTO_STORE)
  }
  localStorage.setItem(CRYPTO_DEVICE_KEY, deviceId)

  await initAsync()

  try {
    machine = await OlmMachine.initialize(
      new UserId(userId),
      new DeviceId(deviceId),
      CRYPTO_STORE,
    )
  } catch (err) {
    if (err instanceof Error && err.message.includes('account in the store')) {
      // First run with no stored device key — nuke and retry
      console.warn('[crypto] Crypto store mismatch, clearing...')
      // Close all IndexedDB connections by deleting via name
      // The failed initialize should not hold connections open
      await deleteDb(CRYPTO_STORE)
      // Also try the internal stores the WASM module creates
      const dbs = await indexedDB.databases()
      for (const dbInfo of dbs) {
        if (dbInfo.name && dbInfo.name.startsWith(CRYPTO_STORE)) {
          await deleteDb(dbInfo.name)
        }
      }
      machine = await OlmMachine.initialize(
        new UserId(userId),
        new DeviceId(deviceId),
        CRYPTO_STORE,
      )
    } else {
      throw err
    }
  }
  initialized = true

  // Bootstrap: upload device keys + one-time keys immediately
  await processOutgoingRequests()
}

export function getCrypto(): OlmMachine | null {
  return machine
}

export function isCryptoReady(): boolean {
  return initialized && machine !== null
}

// --- Process sync response crypto fields ---

export async function processSyncCrypto(response: MatrixSyncResponse): Promise<void> {
  if (!machine) return

  // Feed to-device events, device list changes, and OTK counts to OlmMachine
  // OlmMachine expects a JSON array of events, not the wrapper object
  const toDeviceEvents = JSON.stringify(response.to_device?.events ?? [])

  const changedUserIds = (response.device_lists?.changed ?? []).map((u) => new UserId(u))
  const leftUserIds = (response.device_lists?.left ?? []).map((u) => new UserId(u))
  const deviceLists = new DeviceLists(changedUserIds, leftUserIds)

  const otkCounts = new Map<string, number>()
  if (response.device_one_time_keys_count) {
    for (const [algo, count] of Object.entries(response.device_one_time_keys_count)) {
      otkCounts.set(algo, count)
    }
  }

  const unusedFallbackKeys = response.device_unused_fallback_key_types
    ? new Set(response.device_unused_fallback_key_types)
    : undefined

  const decryptionSettings = new DecryptionSettings(TrustRequirement.Untrusted)

  await machine.receiveSyncChanges(
    toDeviceEvents,
    deviceLists,
    otkCounts,
    unusedFallbackKeys,
    decryptionSettings,
  )

  // Process outgoing requests generated by the sync (key uploads, queries, etc.)
  await processOutgoingRequests()
}

// --- Execute pending outgoing requests ---

async function processOutgoingRequests(): Promise<void> {
  if (!machine) return

  // Loop until drained — processing KeysQuery responses generates KeysClaim
  // requests that must also be executed before key sharing can succeed
  for (let pass = 0; pass < 10; pass++) {
    const requests = await machine.outgoingRequests()
    if (requests.length === 0) break
    for (const req of requests) {
      try {
        await executeRequest(req)
      } catch (err) {
        // Expected for bridge devices — silently skip
      }
    }
  }
}

// Route OlmMachine requests to the correct Matrix API endpoint
async function executeRequest(req: OutgoingRequest): Promise<void> {
  if (!machine) return

  const token = getMatrixAccessToken()
  const hs = getMatrixHomeserver()
  if (!token || !hs) return

  let responseBody: string

  switch (req.type) {
    case RequestType.KeysUpload: {
      const r = req as KeysUploadRequest
      responseBody = await matrixPost(`${hs}/_matrix/client/v3/keys/upload`, r.body, token)
      await machine.markRequestAsSent(r.id, r.type, responseBody)
      break
    }
    case RequestType.KeysQuery: {
      const r = req as KeysQueryRequest
      responseBody = await matrixPost(`${hs}/_matrix/client/v3/keys/query`, r.body, token)
      await machine.markRequestAsSent(r.id, r.type, responseBody)
      break
    }
    case RequestType.KeysClaim: {
      const r = req as KeysClaimRequest
      responseBody = await matrixPost(`${hs}/_matrix/client/v3/keys/claim`, r.body, token)
      await machine.markRequestAsSent(r.id, r.type, responseBody)
      break
    }
    case RequestType.ToDevice: {
      const r = req as ToDeviceRequest
      const url = `${hs}/_matrix/client/v3/sendToDevice/${encodeURIComponent(r.event_type)}/${encodeURIComponent(r.txn_id)}`
      responseBody = await matrixPut(url, r.body, token)
      await machine.markRequestAsSent(r.id, r.type, responseBody)
      break
    }
    case RequestType.SignatureUpload: {
      const r = req as SignatureUploadRequest
      responseBody = await matrixPost(`${hs}/_matrix/client/v3/keys/signatures/upload`, r.body, token)
      if (r.id) {
        await machine.markRequestAsSent(r.id, r.type, responseBody)
      }
      break
    }
    case RequestType.KeysBackup: {
      const r = req as KeysBackupRequest
      const url = `${hs}/_matrix/client/v3/room_keys/keys?version=${encodeURIComponent(r.version)}`
      responseBody = await matrixPut(url, r.body, token)
      await machine.markRequestAsSent(r.id, r.type, responseBody)
      break
    }
  }
}

// --- Decrypt a room event ---

export async function decryptRoomEvent(
  event: MatrixEvent,
  roomId: string,
): Promise<{ type: string; content: Record<string, unknown> } | null> {
  if (!machine) return null
  if (event.type !== 'm.room.encrypted') return null

  try {
    const eventJson = JSON.stringify({
      type: event.type,
      content: event.content,
      event_id: event.event_id,
      sender: event.sender,
      origin_server_ts: event.origin_server_ts,
      room_id: roomId,
    })

    const decryptionSettings = new DecryptionSettings(TrustRequirement.Untrusted)
    const decrypted = await machine.decryptRoomEvent(eventJson, new RoomId(roomId), decryptionSettings)
    const parsed = JSON.parse(decrypted.event)

    return {
      type: parsed.type ?? 'm.room.message',
      content: parsed.content ?? {},
    }
  } catch (err) {
    // Expected when Megolm keys not available — falls back to placeholder
    return null
  }
}

// --- Encrypt a room event for sending ---

export async function encryptRoomEvent(
  roomId: string,
  eventType: string,
  content: Record<string, unknown>,
): Promise<string | null> {
  if (!machine) return null

  try {
    // Ensure we have Megolm sessions shared with room members
    // The OlmMachine handles session management internally
    const encrypted = await machine.encryptRoomEvent(
      new RoomId(roomId),
      eventType,
      JSON.stringify(content),
    )
    return encrypted // JSON string of the encrypted content
  } catch (err) {
    // Falls back to plaintext send
    return null
  }
}

// --- Share room keys with members before encrypting ---

export async function shareRoomKeys(
  roomId: string,
  memberUserIds: string[],
): Promise<void> {
  if (!machine) return

  try {
    // WASM UserId objects are consumed by each call — create fresh instances each time

    // 1. Track users so OlmMachine knows about their devices
    await machine.updateTrackedUsers(memberUserIds.map((id) => new UserId(id)))

    // 2. Process key query requests (fetches device keys from server)
    await processOutgoingRequests()

    // 3. Claim one-time keys to establish Olm sessions with all devices
    //    Best-effort: cloud bridge servers (Beeper) may reject claims for bridge devices
    let claimFailed = false
    try {
      const claimReq = await machine.getMissingSessions(
        memberUserIds.map((id) => new UserId(id)),
      )
      if (claimReq) {
        const token = getMatrixAccessToken()
        const hs = getMatrixHomeserver()
        if (token && hs) {
          const claimResponse = await matrixPost(
            `${hs}/_matrix/client/v3/keys/claim`,
            claimReq.body,
            token,
          )
          await machine.markRequestAsSent(claimReq.id, claimReq.type, claimResponse)
        }
      }
    } catch (err) {
      // Expected for bridge devices — claimFailed flag skips shareRoomKey
      claimFailed = true
    }

    // 4. Process any follow-up requests generated by key claiming
    await processOutgoingRequests()

    // 5. Share Megolm session with room members (now has Olm sessions)
    //    Skip if claim failed — shareRoomKey will WASM-panic without Olm sessions
    if (!claimFailed) {
      const encryptionSettings = new EncryptionSettings()
      const requests = await machine.shareRoomKey(
        new RoomId(roomId),
        memberUserIds.map((id) => new UserId(id)),
        encryptionSettings,
      )

      // 6. Execute key-sharing to-device requests
      const token = getMatrixAccessToken()
      const hs = getMatrixHomeserver()
      if (!token || !hs) return

      for (const req of requests) {
        try {
          const url = `${hs}/_matrix/client/v3/sendToDevice/${encodeURIComponent(req.event_type)}/${encodeURIComponent(req.txn_id)}`
          const responseBody = await matrixPut(url, req.body, token)
          await machine!.markRequestAsSent(req.id, req.type, responseBody)
        } catch (err) {
          // Expected for bridge devices that reject key claims
        }
      }

      // 7. Process any final outgoing requests
      await processOutgoingRequests()
    }
  } catch (err) {
    // Encryption will fall back to plaintext
  }
}

// --- Get missing sessions for a set of users ---

export async function claimMissingSessions(userIds: string[]): Promise<void> {
  if (!machine) return

  const claimReq = await machine.getMissingSessions(
    userIds.map((id) => new UserId(id)),
  )
  if (!claimReq) return

  const token = getMatrixAccessToken()
  const hs = getMatrixHomeserver()
  if (!token || !hs) return

  const responseBody = await matrixPost(
    `${hs}/_matrix/client/v3/keys/claim`,
    claimReq.body,
    token,
  )
  await machine.markRequestAsSent(claimReq.id, claimReq.type, responseBody)
}

// --- Low-level HTTP helpers (bypass api.ts to avoid circular deps) ---

async function matrixPost(url: string, body: string, token: string): Promise<string> {
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body,
  })
  const text = await res.text()
  if (!res.ok) throw new Error(`Matrix POST ${res.status}: ${text}`)
  return text
}

async function matrixPut(url: string, body: string, token: string): Promise<string> {
  const res = await fetch(url, {
    method: 'PUT',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body,
  })
  const text = await res.text()
  if (!res.ok) throw new Error(`Matrix PUT ${res.status}: ${text}`)
  return text
}

// --- Cross-signing bootstrap & device verification ---

export async function getCrossSigningStatus(): Promise<{
  hasMaster: boolean
  hasSelfSigning: boolean
  hasUserSigning: boolean
  deviceVerified: boolean
}> {
  if (!machine) return { hasMaster: false, hasSelfSigning: false, hasUserSigning: false, deviceVerified: false }

  const status = await machine.crossSigningStatus()
  let deviceVerified = false
  try {
    const device = await machine.getDevice(machine.userId, machine.deviceId)
    if (device) {
      deviceVerified = device.isCrossSigningTrusted()
      device.free()
    }
  } catch { /* ignore */ }

  return {
    hasMaster: status.hasMaster,
    hasSelfSigning: status.hasSelfSigning,
    hasUserSigning: status.hasUserSigning,
    deviceVerified,
  }
}

export async function bootstrapAndVerifyDevice(password: string): Promise<string> {
  if (!machine) throw new Error('Crypto not initialized')

  const token = getMatrixAccessToken()
  const hs = getMatrixHomeserver()
  const userId = getMatrixUserId()
  if (!token || !hs || !userId) throw new Error('Not connected to Matrix')

  // Bootstrap: generate new cross-signing keys
  console.log('[crypto] Bootstrapping cross-signing keys...')
  const requests = await machine.bootstrapCrossSigning(true)

  // 1. Upload device keys if needed
  if (requests.uploadKeysRequest) {
    const resp = await matrixPost(
      `${hs}/_matrix/client/v3/keys/upload`,
      requests.uploadKeysRequest.body,
      token,
    )
    await machine.markRequestAsSent(
      requests.uploadKeysRequest.id,
      requests.uploadKeysRequest.type,
      resp,
    )
  }

  // 2. Upload cross-signing public keys (requires UIA with password)
  await uploadSigningKeysWithUIA(hs, token, userId, password, requests.uploadSigningKeysRequest.body)
  console.log('[crypto] Cross-signing keys uploaded')

  // 3. Upload signatures (self-signing key signs our device)
  const sigResp = await matrixPost(
    `${hs}/_matrix/client/v3/keys/signatures/upload`,
    requests.uploadSignaturesRequest.body,
    token,
  )
  if (requests.uploadSignaturesRequest.id) {
    await machine.markRequestAsSent(
      requests.uploadSignaturesRequest.id,
      requests.uploadSignaturesRequest.type,
      sigResp,
    )
  }
  console.log('[crypto] Device self-signed via bootstrap')

  // 4. Generate new recovery key and upload cross-signing keys to SSSS
  let recoveryKey: string
  try {
    const { generateNewRecoveryKey } = await import('./key-backup')
    recoveryKey = await generateNewRecoveryKey()
    // Recovery key generated
  } catch {
    // Non-fatal — verification still succeeds
    recoveryKey = '(failed to generate — re-run verification)'
  }

  // 5. Verify all other devices
  const count = await verifyAllDevices()
  console.log('[crypto] Verified', count, 'other devices')

  // Process any follow-up outgoing requests
  await processOutgoingRequests()

  return recoveryKey
}

// Upload cross-signing keys with User Interactive Auth (password)
async function uploadSigningKeysWithUIA(
  hs: string,
  token: string,
  userId: string,
  password: string,
  body: string,
): Promise<void> {
  // First attempt without auth to get the session ID
  const firstRes = await fetch(`${hs}/_matrix/client/v3/keys/device_signing/upload`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body,
  })

  if (firstRes.ok) return

  if (firstRes.status === 401) {
    const uiaInfo = await firstRes.json()
    const session = uiaInfo.session

    const bodyWithAuth = {
      ...JSON.parse(body),
      auth: {
        type: 'm.login.password',
        identifier: { type: 'm.id.user', user: userId },
        password,
        session,
      },
    }

    const secondRes = await fetch(`${hs}/_matrix/client/v3/keys/device_signing/upload`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(bodyWithAuth),
    })

    if (!secondRes.ok) {
      const text = await secondRes.text()
      throw new Error(`Failed to upload signing keys: ${secondRes.status}: ${text}`)
    }
  } else {
    const text = await firstRes.text()
    throw new Error(`Failed to upload signing keys: ${firstRes.status}: ${text}`)
  }
}

// Self-sign the current device using existing cross-signing keys
async function selfSignDevice(): Promise<void> {
  if (!machine) return

  const token = getMatrixAccessToken()
  const hs = getMatrixHomeserver()
  if (!token || !hs) return

  const device = await machine.getDevice(machine.userId, machine.deviceId)
  if (!device) throw new Error('Could not find own device')

  try {
    if (device.isCrossSigningTrusted()) {
      console.log('[crypto] Device already cross-signing trusted')
      return
    }

    const signatureRequest = await device.verify()
    const resp = await matrixPost(
      `${hs}/_matrix/client/v3/keys/signatures/upload`,
      signatureRequest.body,
      token,
    )
    if (signatureRequest.id) {
      await machine.markRequestAsSent(signatureRequest.id, signatureRequest.type, resp)
    }
    console.log('[crypto] Device self-signed with cross-signing key')
  } finally {
    device.free()
  }
}

// Try to self-sign device after key backup restore (if cross-signing keys were imported)
export async function trySelfSignAfterKeyImport(): Promise<void> {
  if (!machine) return
  try {
    const status = await machine.crossSigningStatus()
    if (status.hasSelfSigning) {
      await selfSignDevice()
    }
  } catch (err) {
    // Non-critical — device will work without self-signing
  }
}

// Verify all user devices using our cross-signing keys
export async function verifyAllDevices(): Promise<number> {
  if (!machine) throw new Error('Crypto not initialized')

  const token = getMatrixAccessToken()
  const hs = getMatrixHomeserver()
  if (!token || !hs) throw new Error('Not connected to Matrix')

  const status = await machine.crossSigningStatus()
  if (!status.hasSelfSigning) {
    throw new Error('No cross-signing keys loaded — verify this device first')
  }

  // Query all devices from the server so OlmMachine knows about them
  await machine.updateTrackedUsers([new UserId(machine.userId.toString())])
  await processOutgoingRequests()

  // Get all our devices
  const devicesMap = await machine.getUserDevices(machine.userId)
  const devices = devicesMap.devices()
  let verified = 0

  for (const device of devices) {
    try {
      if (device.isCrossSigningTrusted()) {
        continue
      }
      const signatureRequest = await device.verify()
      const resp = await matrixPost(
        `${hs}/_matrix/client/v3/keys/signatures/upload`,
        signatureRequest.body,
        token,
      )
      if (signatureRequest.id) {
        await machine.markRequestAsSent(signatureRequest.id, signatureRequest.type, resp)
      }
      verified++
    } catch {
      // Device may already be verified or unreachable
    } finally {
      device.free()
    }
  }
  devicesMap.free()

  await processOutgoingRequests()
  return verified
}
